# Aineisto

## Tutkitut kyläyhteisöt

Esittelen seuraavaksi käsittelemäni kyläyhteisöt. Kyseessä ovat monin
tavoin hyvin samanlaiset asutukset, joten käyn ensin läpi niiden
yhteisiä piirteitä, minkä jälkeen esittelen ne yksityiskohtaisemmin
erikseen. Molemmat kylät ovat vanhoja asutuksia, sillä Tuuksa
mainitaan ensimmäisen kerran 1500-luvulla (Koćkurkina 1994: 6) ja
Koigort vuonna 1586 (Žerebtsov 2000). Nämä on saatettu joskus ymmärtää
kylien perustamisvuosiksi, mutta ilmeisesti tämä kertoo lähinnä noina
aikoina kasvaneesta hallinnollisesta kirjanpitotyöstä. Kylien voi
olettaa olevan tätä vanhempia.

Valitettavasti minulla ei ole tarkkaa tietoa kummankaan kylän
demografisesta rakenteesta. Yleisvaikutelmasta voi sanoa, että nuoria
tuntuu olevan verrattain vähän suhteessa muuhun väestöön. Tämä
selittyy kylien rajallisilla opiskelu- ja työmahdollisuuksilla. Nuoret
muuttavat pääsääntöisesti opiskelemaan suurempiin kaupunkeihin, joista
harva enää palaa. Tämä heijastuu voimakkaasti omassa aineistossani,
jossa nuoret ikäluokat ovat aliedustettuina. Tähän liittyy myös
metodologisia valintoja ja ongelmia, joita käyn läpi luvussa X
analysoidessani aineistonkeruun menetelmiä ja haasteita.

Molempia yhteisöjä ovat myöhemminkin koskettaneet osin samanlaiset
valtapoliittiset päätökset. Erityisesti 1950-luvun jälkeen molempiin
kyliin on tullut uutta väestöä Neuvostoliiton koulutuspolitiikan
myötä, sillä korkeakoulusta valmistuneet eivät saaneet itse valita
työpaikkojaan vaan heidät lähetettiin kolmeksi vuodeksi tiettyihin
työkohteisiin. Tuuksen asukkaista moni on syntyisin muualta
Karjalasta, esimerkiksi Viteleeltä tai Kuujärveltä, mutta moni on
tullut kauempaa Venäjältä. Suuri demografinen muutos tapahtui
perspektiivittömiksi katsottuja kyliä lakkauttaessa. Sekä Tuuksa että
Koigort ovat keskuksia, joihin suljettujen kylien väestöä on
siirretty. Koko Karjalassa oli hävinnyt jo vuoteen 1959 tultaessa
2973:sta kylästä 1553, eli siis yli puolet. Vuonna 1989 kyliä oli enää
668. (Klementjev 2008: 61–62). Komissa vuosina 1970–1989 hävisi yli
300 kylää (Žerebtsov 2006). Ero selittynee Karjalan tiheämmällä
asutuksella. Tuukseen on tullut 1970-luvulla ihmisiä eritoten Viteleen
ja Aunuksen väliin jäävistä kylistä, Koigortiin taas eteläisemmästä
Kobrasta ja Koigortia lähellä sijainneista pienemmistä asutuksista.

### Tuuksa

Tuuksen kylä sijaitsee Karjalan tasavallan Aunuksen piirin
eteläosassa1. Matkaa Aunuksen kaupunkiin on alle kymmenen
kilometriä. Kyläyhteisönä Tuuksa edustaa alueelle tyypillistä
joenvarren asutusta. Talot levittäytyvät pitkälle alueelle, ja
yksittäiset pikkukylät saattoivat muodostua yksittäisistä taloista. Jo
vuodelta 1887 on kirjoituksia, joiden mukaan Tuuksessa olisi ollut
kyliä 37, asukkaita 1930 ja talouksia 338. Toisen lähteen mukaan
vuonna 1926 Tuuksen kyläneuvoston alueella oli 19 kylää, joissa oli
1435 asukasta 351 taloudessa2. Tällä hetkellä Tuuksessa asuu
paikallisten asukkaiden arvioiden mukaan 700–1300 henkeä. Tämä antaa
jonkinlaisen suuruusluokan. Kylämäisen asutuksen levittäytyessä
laajalle on vaikea saada tietoa siitä, millä alueella tarkalleen näin
suuri väkijoukko asuu, minkä lisäksi Venäjällä moni pitää itseään
kirjoilla synnyinpaikkakunnallaan muutettuaan muualle esimerkiksi
opiskelemaan.

Tuuksen varsinainen modernisoituminen alkoi 1920-luvulla. Tällöin
esimerkiksi peltotöissä otettiin käyttöön traktoreita. Kylä kasvoi ja
50-luvulla kaksi kolhoosia yhdistettiin. Kylään vedettiin tällöin
sähköt. Kylään rakennettiin koulu vuonna 1957, jolloin oppilaita oli
300. Ihmisten kertomuksissa tähän viitataan vanhana kouluna, jossa
toimi myös päiväkoti. Nykyinen koulurakennus on rakennettu tällä
vuosituhannella. Nykyään oppilaita on noin 150, esimerkiksi vuonna
2007 heitä oli 166 (Oma Mua 28.6.2007). 1900-luvun jälkipuoliskolla
aiemmin kasvanut väestö on alkanut pienentyä.

```{r, echo=F}
library(ggmap)

```


Kartta 2. Tutkittu alue alhaalla keskellä. Aunus alhaalla
oikealla. (Kahden ruudun väli n. 10 km.) Käytän kartassa ja tekstissä
suomenkielisiä nimiä. Lähde: maps.vlasenko.net

Jätän informanttien anonymiteetin säilymisen vuoksi määrittelemättä
aivan tarkan kylänosan, jossa työskentelimme. Alueen asukkaat ovat
kotoisin joko Tuuksesta tai lähikylistä. Rakennuskanta on verrattain
uutta, siten että vanhimmat rakennukset sijaitsevat joen varrella,
mutta monin paikoin remontoidaan vanhoja ja rakennetaan uusia
taloja. Tuuksen keskustassa olevat kerrostalot puolestaan rakennettiin
1980-luvun alussa, jolloin niihin siirrettiin paljon väestöä pienistä
kylistä sovhooseihin. Kuten kartta 2 osoittaa, on kylämäinen asutus
lähes yhtenäinen Tuuksesta Aunukseen. Suuri osa tästä asutuksesta on
kuulunut samaan vanhaan livvinkieliseen kyläverkostoon. Nykyäänkin
Tuuksen alueen ihmiset ovat liikkuneet paljon kylistä toisiin. Monet
haastatellut tai heidän vanhempansa ovat syntyneet lähikylissä. Tämä
on tyypillistä myös kesinä 2012 ja 2013 tavatuille informanteille,
usein vanhemmista tai isovanhemmista toinen oli kotoisin joidenkin
kymmenien kilometrien säteeltä eri kylistä. Tämä on hyvin
pienimuotoista liikehdintää, joka lienee ollut tyypillistä
perinteisille maatalouspainotteisille yhteisöille jo hyvin
kauan. Nähtävästi Tuuksesta on jo varhain ollut muuttoliikettä
Aunukseen. Nykyäänkin tuuksalaisia vaikutti käyvän täällä
töissä. Pidempisuuntaista muuttoliikettä kuvaa yksittäisten
vienankarjalaisten asettuminen kylään. Paikalliset tuukselaiset ovat
maininneet, että jopa joidenkin kilometrien välimatkoilla olisi
tiedostettuja murre-eroja. Tämänkin puolesta paikallisten
kielimuotojen jatkotutkimus olisi tärkeää.

Ensimmäiset haastatellut kylään muuttaneet venäläiset ovat muuttaneet
tänne 1950-luvulla. Tästä alkaen kylään asettui myös
inkerinsuomalaisia, lyydiläisiä ja vepsäläisiä. Käsittelen
tutkimuksessani myös heidän kielellisiä valintojaan tässä
yhteisössä. On epäselvää, kuinka paljon venäläisiä kylään oikeastaan
on muuttanut. Erityisesti nyt tutkituilla alueilla asuu lähinnä
yksittäisiä muuta kuin karjalaa äidinkielenään puhuvia.

### Koigort

Koigorodok on noin 3000 asukkaan kylä Komin tasavallan eteläosassa. Se
on Koigorodokin piirin hallinnollinen keskus. Käytän tässä
tutkimuksessa siitä kominkielestä nimeä Koigort. Tuuksen tapaan sekin
sijaitsee joen varrella, mutta suuri osa asutuksesta näyttää
keskittyvän Sysola-joen vanhan uoman varrelle. Komissa on hyvin
tyypillistä, että joet vaihtavat uomaansa yksittäistenkin ihmisten
elinaikana. Tuuksasta Koigort eroaa eritoten suurempien
asutuskeskusten etäisyydellä. Siinä missä Tuuksesta Aunukseen ulottuu
pienten kylien lähes jatkuva rivi, on Koigort eristyksissä Komin
tiheämmin asutuista alueista. Tämä näkyy hyvin samaan mittakaavaan
tehdyltä kartalta 3. Lähikyliä ovat Koigortin kylästä kymmenen
kilometrin päässä pohjoisessa sijaitsevat Užgan kylä ja kahdenkymmenen
kilometrin päässä Grivan kylä. Nämä ovat pienemmät 200 ja
400. Koigortissakin. Kartan vasemmassa alakulmassa on sijainnut Kobran
kylä, joka kuuluu samaan murrealueeseen. Muut etelässä sijaitsevat
kylät kuten Kom, Kuźjol’ ja Voktym edustavat uudempaa rakennuskantaa –
ensimmäinen on 30-luvulla ja toinen 50-luvulla rakennettu
metsänhakkuutaajama (Žerebtsov 2000: 183, 390). Užgan lähellä
sijaitsee myös metsätyötaajamaksi perustettu Śödtydin. Oma lukunsa on
noin 35 kilometrin päässä sijaitseva Kažym, joka on perustettu vuonna
1755 rautatehtaan ympärille (Žerebtsov 2000: 126).

Olen selkeyden vuoksi merkinnyt oheiseen karttaan näiden kylien
perustamisvuodet. Olen merkinnyt lakkautetut kylät punaisella
reunuksella. En ole tehnyt vastaavia merkintöjä karttaan 2, sillä
minulla ei ole valitettavasti ollut käytössäni riittäviä tietoja
tällaiseen kuvaukseen koko alueelta Karjalassa. Metsätyötaajamiin
tuotiin työntekijöitä Komin tasavallan ulkopuolelta, mutta kaikkien
kolhoosien täytyi myös toimittaa näihin työntekijöitä. 30-luvulla
Komin metsissä työskentelikin jo 30 000 henkeä. (GTZ: The timber
cutting…). Tämä kytkee ulkopuolisella työvoimalla perustettuja leirejä
paikallisyhteisöihin. Myös Komin historiaa tutkinut Žerebtsov on
kuvaillut Komissa olleen kaksi paralleelista teollista järjestelmää,
joista toinen, työleirien verkosto, ei ollut kytköksissä paikalliseen
väestöön. Metsätyöleirit puolestaan olivat. (Žerebtsov
2005). Työleirejä eli gulageja ei ole ollut Koigortin välittömässä
läheisyydessä. Toisaalta on mainittava, että myös Karjalassa oli
todella paljon metsätyöleirejä, nähtävästi vain huomattavasti vähemmän
Aunuksen piirissä ja Tuuksen lähellä.

Seuraavan sivun kartta havainnollistaa Koigortin sijaintia muihin
naapurikyliin. Nimet on translitteroitu komilaisista
nimistä. Punertavalla värillä on taas merkitty alueet, joilla
tutkimusta on tehty. Aiemmin esittämästäni Tuuksen kartasta poiketen
tähän on merkitty kylien perustamisvuosia. Ne olivat helposti
selvitettävissä (Žerebtsov 2000), ja niissä olleet suuret erot saivat
tämän tuntumaan tärkeältä lisätiedolta.

Kartta 3. Koigorodok keskellä alhaalla ja Griva vasemmassa
yläkulmassa. Uusi tie puuttuu kartasta. (Kahden ruudun väli n. 10 km.)
Kartta: maps.vlasenko.net

Nykyinen Koigortin taajama on kasvanut melko äskettäin vanhojen
pienempien kylien päälle, mistä kertovat nykyiset kylänosat Kurgan ja
Pogost, joita paikalliset asukkaat yhä mieltävät eri kyliksi. Aiemman
Komissa tehdyn työn perusteella tämä vaikuttaa tyypilliseltä
kehitykseltä nopeasti kasvaneille piirikeskuksille. Pogostan
pohjoispuolella sijaitseva Vador on uudempaa aluetta, ja meille
kerrottiin siellä sijainneen aiemmin pääasiassa suota. Maata
kohotettiin, kun teitä rakennettiin 50-luvulla. Koigortin kylän
vieressä on 1930-luvulla perustettu ja 1950-luvulla nopeasti kasvanut
Koidinin taajama (Žerebtsov 2000: 150), jonka paikalla on aiemmin
ollut Bazana tunnettu kylänosa. Koidiniä kuvaillaan lähtökohtaisesti
venäjänkieliseksi. Valitettavasti en ehtinyt työskentelemään
Koidinissä, mutta olen haastatellut muualle Komin tasavaltaan
muuttanutta täällä 1950-luvulla syntynyttä miestä. Hän puhuu
aktiivisesti vain venäjää, mutta osaa jonkin verran myös komia. Hän
kuvaili, kuinka ainoastaan isovanhemmat puhuivat hänelle komia. Tämä
sopii muualta saatuun kuvaukseen tällaisista metsätöiden ympärille
perustetuista taajamista, eikä ole suoraan verrattavissa muihin alueen
perinteisesti kominkielisiin yhteisöihin.

Nyt haastateltiin lähinnä ihmisiä, jotka asuivat Pogostan
kylänosassa. Alue on kilometrien pituinen, joten tämä tieto ei vielä
paljasta tarkkoja kohteina olleita katuja. Tämä koko alue on Koigortin
vanhempaa rakennuskantaa. Alueen iäkkäimmät talot ovat noin
satavuotiaita, eikä uusia taloja ole juurikaan rakennettu. Tämä on
alue, jossa yksittäiset nuoretkin informantit arvelivat komien
asuvan. Tämä oli yksi tärkeä syy sille, että päädyin työskentelemään
juuri tällä alueella. Tämä on keskeinen ero Koigortista ja Tuuksesta
valittujen tutkimuskohteiden välillä, sillä Tuuksessa työ tehtiin
pääasiassa uudemman rakennuskannan alueella. Jälkikäteen ajatellen
olisi ollut viisasta keskittää tutkimus Koigortissakin hieman
uudempaan kylänosaan, mutta valitettavasti tällaisia päätöksiä on
vaikea tehdä itse tutkimustilanteessa, jota aloitettaessa kylää ei
vielä tunneta juurikaan.

Koigortin väestö on kasvanut viime aikoina. Erityisesti nuoret perheet
rakentavat taloja kylän itäpuolella sijaitseville mäille. Syitä
talojen rakentamiseen ovat muun muassa vanhan rakennuskannan
hajoaminen sekä asuntojen kalleus. Nuorille perheille tulee paljon
edullisemmaksi rakentaa talo kuin ostaa asunto kaupungista. Monet
vanhat talot saattavat yhä olla hyvässä kunnossa, mutta tällöinkään
niiden varustelutaso ei välttämättä vastaa viime vuosikymmeninä
nousseita vaatimuksia. Tämä ei tarkoita, että Koigort olisi
varsinainen kasvukeskus tai että työmahdollisuudet olisivat missään
mielessä poikkeuksellisen hyvät. Minulle kerrottiin kuitenkin, että
lähiseudulla sijanneista metsätyötaajamista on viimekin vuosina
muuttanut taloja rakentavia nuoria perheitä Koigortiin. Haastattelin
jonkin verran taloja rakentaneita nuoria, ja käsittelen
haastatteluista saatuja tietoja tarkemmin itse aineiston analyysin
yhteydessä luvussa X.X.Verkosto Komi X.

Etnografisista haastatteluista käy selkeästi ilmi, että Koigort, Užga
ja Griva ovat muiden jo hävinneiden kylien (Venib, Myrponayb, Katyd ja
Vadyb) kanssa muodostaneet aiemmin yhteisön, jonka sisällä on liikuttu
säännöllisesti kylistä toisiin. Erityisen tärkeitä tälle liikkumiselle
näyttävät olleen säännölliset juhlat, joiden vuotuiskierron mukaan
vierailtiin aina tietyissä kylissä. Vanha tie kulki kylien halki, ja
uudet asfaltoidut tiet rakennettiin vasta sodan jälkeen. Myös autot
alkoivat yleistyä tässä vaiheessa. Ennen tätä matka Grivan ja
Koigortin välillä kesti jalkaisin kolme tuntia, Koigortin ja Venibin
väli kaksi tuntia. Tämä vuorovaikutus näyttää rajoittuneen tälle
akselille, eikä ole ulottunut mainittavasti tästä muihin
ilmansuuntiin. Samalla tälle alueelle rajoittuu komin Ylä-Sysolan
murteen levikki, mikä osaltaan vahvistaa käsitystäni näiden kylien
tiiviistä kuulumisesta yhteen. Kaikki iäkkäämmät Koigortissa kasvaneet
informantit muistivat käyneensä nuorina Grivassa asti, jonne on vanhaa
tietä pitkin noin 40 kilometrin matka. Myös nyt jo hävitetty Kobran
kylä on kuulunut tähän samaan verkostoon. Vielä 60–70 -luvuilla
esimerkiksi Mihailinpäivää vietettiin Kobrassa, mutta noihin aikoihin
perinteinen liikehdintä kylien välillä on mitä ilmeisimmin jo alkanut
katketa.

Suomalainen tutkija Anders Sjögren vieraili alueen kylissä vuonna
1827. Tarkalleen hän kävi Užgassa, Koigortissa ja Kažimissa. Hänen
muistiinpanoistaan löytyy tieto siitä, että Koigort oli eteläisin
hänen löytämänsä komilainen kylä. Hän kertoo muistiinpanoissaan, että
Uzhgassa ja Koigortissa monet eivät osanneet venäjää. Kažim ei hänen
mukaansa ollut vanhaa komien aluetta, mutta myös sieltä löytyi
Koigortista kotoisin olleita syrjäänimiehiä, jotka olivat tulleet
tänne rautatehtaaseen töihin. Sjögrenin vierailun aikana rautatehtaan
perustamisesta oli kulunut jo yli 70 vuotta. Hän vieraili alueella
vuoden 1827 elokuussa päivinä 8–21. (Ks. lisätietoa Branch 1973.)
Sjögrenin tieto Koigortista alueen eteläisimpänä komilaisena kylänä
viittaisi siihen, että nykyiset Koigortin eteläpuoliset
asutuskeskukset (Kom, Voktym, Il’za) olisivat tosiaan syntyneet vasta
1930-luvun jälkeisinä metsätyötaajamina, ilman että paikoilla olisi
ollut vanhempaa komilaista asutusta. Aineistossani on kuvauksia
kaikista näistä kylistä, ja nämä viittaavat kaikki
venäjänkielisyyteen.

Mainitsin jo edellä lakkautettujen kylien merkityksestä. Koigortin
nykyisen väestön demografiaan on vaikuttanut, että 540 asukkaan Kobran
kylä lakkautettiin vuonna 1973. Informanttien joukossa on hyvin paljon
kobralaisia tai heidän jälkeläisiään.. Kylien lakkautus on siten yhä
käynnissä, että eteläisempien metsätyötaajamien kuten Voktymin
lakkauttamista suunnitellaan nytkin. Käsittelen lyhyesti Kobran ja
Grivan kyliä, sillä ne ovat selvästi Koigortin lisäksi merkittävimmät
komilaiset asutuskeskukset alueella, eikä Kobrankaan merkitys
välttämättä ole täysin hävinnyt kylän tultua lakkautetuksi.

### Kobran kylä esimerkkinä 

Käsittelen lyhyesti Kobran kylästä saamiani tiedonantoja, sillä se
havainnollistaa hyvin Etelä-Komissa 1700–1800-luvuilla käynnissä
olleita väestönliikkeitä. Ylä-Sysolalta tulleet uudisasukkaat
perustivat Kobran kylän vuonna 1747. Tämä on nähtävissä sekä kylän
murteesta että perinnekulttuurista. Kylä sijaitsi 64 kilometrin päässä
Koigortista (Žerebtsov 2000: 146). Se sijaitsee Kobra-joen varrella,
joka Sysolasta poiketen on Vjatkan sivujokia ja laskee siis
etelään. Kobrasta on linnuntietä Kiroviin 170 kilometriä, Vjatkaa
pitkin luultavasti monta sataa kilometriä. Kirov on silti ollut Kobran
asukkaille tärkeämpi kauppakeskus kuin Syktyvkar. Eräskin kobralainen
informantti muisteli, kuinka Kirovista haettiin veneitä jokea
pitkin. Aiemmin hän kertoi tarinan, että Kobralla olisi ennen asunut
venäläisiä, mutta näiden ajan mittaan kuoltua jäi jäljelle enää
komeja:

Näyte 1. Informantti 40, nauha 147, [00:13:07], 1.7.2012

Kobran murteen venäläisyydet on jo varhain pantu merkille. On
esimerkiksi väitetty, että venäläisperäisiä äänteitä f ja h voi pitää
Kobran murteessa omina foneemeinaan (Žilina 1975: 14). Näin
luultavasti onkin, sillä muun muassa Kobran kylänosien nimissä nämä
äänteet ovat yleisiä. Kylänosat kuten Hutov ja Pöt’inök ovat selvästi
lähtöisin venäjän yksittäistaloa ja tilusta tarkoittavista sanoista
хутор ja починок. Tämä viittaisi vielä lähimenneisyydessäkin
venäläisten assimiloituneen komeihin.

Kobran kylä lakkautettiin vuonna 1973, jolloin asukkaita oli 563
(Bondarenko 2000: 235–236). Kobrasta on siirretty kokonaisia taloja
Koigortiin. Kobrasta lähtöisin olleita sukulaisia asui usein lähellä
toisiaan. Tämä tarkoittaa, että kylän lakkauttaminen ei ole täysin
tuhonnut Kobrassa merkityksellisiä sosiaalisia verkostoja, vaan
kominkieliset suvut ja naapurikunnat ovat sulautuneet muutamassa
sukupolvessa Koigortin väestöön. Eräskin informantti oppi venäjää
vasta aikuisiällä muutettuaan Kobrasta kaupunkiin
opiskelemaan. Toisaalta hän kertoi vanhempiensa ja isovanhempiensa
osanneen venäjää, ollen itse jopa erittäin hämmästynyt asiaa
kysyessäni, ikään kuin asia olisi itsestään selvä. Kobra jakautui
kolmeen eri kylään ja lukuisiin kylänosiin. Kobran tutkiminen olisi
tietysti jo aivan oma aiheensa, mutta vielä joitain vuosia teoriassa
täysin mahdollista runsaan kobralaisen väestöpohjan yhä
eläessä. Palaan Kobraan tarkastellessani koigortlaisten kielellisiä
verkostoja luvussa X.

### Grivan kylä poikkeuksena

Jos Kobran kylä olikin suurin lakkautettu kylä, on yhä olemassa oleva
Griva myös erityisen huomion arvoinen. Muista alueen kylistä poiketen
se on säilynyt pääasiassa kominkielisenä. Tämä tiedostettiin vahvasti
naapurikylissä, ja esimerkiksi Koigortissa tutkimusryhmäämme
kehotettiin jatkuvasti menemään Grivaan. Grivassa on tällä hetkellä
noin 450 asukasta, joten se on huomattavasti Koigortia pienempi. Griva
on nyt hieman erillään muista kylistä, mutta perinteisesti sen lähellä
on ollut paitsi komilaisia kyliä niin myös metsätyötaajamia. Näistä
esimerkiksi Vokvadin taajamassa on asunut jopa tuhat henkeä, tieto,
jonka useampi grivalainen informantti toisti toisistaan tietämättä.

Griva vertautuu mielenkiintoisella tavalla Kobran kylään, sillä senkin
paikannimistöä hallitsee venäjästä ja komista lähtöisin olevien
paikannimien päällekkäisyys. Läsnä on tämän tiedon jättämä
ambivalenttius – nykyiset asukkaat määritellään yksiselitteisesti
komeiksi.

Näyte 2, Informantti 72, nauha 180. 6.7.2012.

Koigort on kylänä kasvanut viime vuosikymmeninä, mutta Griva on
pienentynyt. Vielä 1960-luvulla Grivan koulussa oli yli 200 oppilasta,
mutta nyt heidän määränsä on vain 46. Lapset vaihtavat koulua Grivasta
Koigortiin seitsemännen luokan jälkeen. Tällä hetkellä kaikki
opettajat koulussa ovat komeja. Jopa vieraiden kielten opettaja on
Užgasta kotoisin oleva komi. Paikallisessa päiväkodissa on yksi
venäläinen työntekijä. Eräs informantti arveli, että Grivaan muuttaa
uusia ihmisiä lähinnä nimitettyihin virkoihin. Mainittiin, että
Grivassa asui jossain vaiheessa azerbaidzanilainen perhe. Ilmeisesti
heidänkin lapsensa oppivat Grivassa komia. Kukaan haastateltu kylän
asukas ei uskonut, että Grivassa olisi enää venäjää osaamattomia
asukkaita. Grivassa työskenneltiin ainoastaan yhtenä päivänä, joten
aineisto on liian pieni kattavammalle käsittelylle.

## Tutkimuksen materiaali

Tutkielmassa käyttämäni aineisto pohjautuu Karjalassa Tuuksessa
(toukokuu 2012 ja kesäkuu 2013) ja Komin tasavallassa sijaitsevassa
Koigortissa (heinäkuu 2012) tehtyyn kenttätyöhön. Komissa työ
toteutettiin yhdessä Syktyvkarin yliopiston opiskelijoiden
kanssa. Tuuksessa työskenneltiin kaksi noin viikon mittaista jaksoa ja
Koigortissa kymmenen päivää. Erityisesti Koigortissa tehtiin
tutkimusta myös lähikylissä, joiden haastattelut on otettu
tutkimuksessa huomioon. Valitettavasti Koigortissa meillä ei ollut
useinkaan mahdollisuutta jatkaa kenttätöiden alussa tehtyjä
haastatteluja myöhemmin. Tuuksessa puolestaan yksittäisten
informanttien haastattelut rakentuvat useamman päivän
tapaamisista. Aineiston lyhyt keruuaika luo monenlaisia ongelmia. Yksi
muuttuja on, että paikallisyhteisö ei ehtinyt näin lyhyenä aikana
tottua ulkopuolisten tutkijoiden läsnäoloon. Ei ole millään muotoa
selvää, kuinka tutkijoiden läsnäolo on vaikuttanut informanttien
käyttäytymiseen ja vastauksiin. Pidempänä ajanjaksona tutkijaan
kiinnitetty huomio voi vähentyä, mikä pienentää ulkopuolisen
havainnoijan aiheuttamaa ongelmaa [@blommaertEtAl2010a,
27–28]. Samalla tulee mahdolliseksi vertailla työn eri vaiheissa
kerättyä aineistoa, erityisesti nauhoituksia [@blommaertEtAl2010a,
31].

### Aineiston keruumetodit

Aineistoa on kerätty lukuisia erilaisia metodeja hyödyntäen. Näihin
lukeutuvat sosiolingvistiset ja etnografiset haastattelut, joita
täydennettiin osallistuvalla havainnoinnilla. Sosiolingvistiset
haastattelut olivat osittain strukturoituja, siten että niissä
kaikissa käytettiin pohjaltaan samanlaista kyselykaavaketta [Karjala:
Liite 1, Komi: Liite 2]. Kyselykaavake on lomaketyyppinä analysoiva,
siten että se keskittyy numeroitavan tiedon sijasta ilmiön syitä ja
motiiveja selittäviin avoimiin kysymyksiin [@oppenheim2006a,
13]. Haastatteluissa on tavoiteltu normaalia keskustelutilannetta. Eri
kysymykset on esitetty keskustelun kululle luontevassa järjestyksessä,
siten että informantti on saanut rajatussa määrin kuljettaa
keskustelua häntä itseään kiinnostavaan suuntaan. Tietyssä mielessä
haastattelut muistuttavatkin William Labovin moduuli-pohjaista
haastattelumallia, jossa on mahdollista siirtyä saumattomasti aiheesta
toiseen (Milroy & Gordon 2003: 58–59). Keskityn tässä tutkimuksessa
aineiston osiin, jotka ensi silmäyksellä voivat vaikuttaa lähes liian
yksinkertaisesti kyllä-ei -vastaustyyppiä noudattelevilta. Taulukkoina
ja kaaviona esitetty aineisto koostuu näennäisesti rakseista
ruutuihin, mutta tämä on kaukana totuudesta. Käytännössä aineisto on
huomattavasti tätä vaikeampitulkintaisempaa. Vastaukset, kuten
kysymyksetkin, ovat sidoksissa tiettyihin hetkiin haastatteluissa,
eikä vastaus läheskään aina ole ollut kyllä tai ei. Käytännössä
pidemmistä narratiiveista on jouduttu yksinkertaistamaan melko paljo,
minkä takia täydennän analyysia esittelemällä juuri tätä kaaviosta
piiloutuvaa diskurssia.

Etnografiset haastattelut kytkeytyivät teemoiltaan kylän historiaan ja
yhteisön perinteiseen elämäntapaan. Etnografia saattaa olla
harhaanjohtava termi näille haastatteluille, sillä kerääjillä ei ollut
etnografista koulutusta. Yleisemmin tätä työskentelytapaa voi
luonnehtia kansatieteellisiksi haastatteluiksi, joiden tavoitteena on
ollut kartoittaa kokonaisvaltaisesti yhteisön materiaalista kulttuuria
ja muistitietoa. Näin ollen ne vertautuvat hyvin 1900-luvun aikana eri
sukukielten parissa harjoitettuun haastatteluperinteeseen, joiden
keskeisin tarkoitus oli murreaineiston kartuttaminen. Etnografisten
haastattelujen suurempi määrä Komissa näkyy epäsuhtana Tuuksen ja
Koigortin aineistoissa. Varsinaisesti kielisosiologista dataa on
jälkimmäisestä usein huomattavasti vähemmän. Toisaalta tämä
muistitietoa käsittelevä aineisto mahdollistaa Koigortin
historiallisen kontekstin hyvän hahmottamisen. Otan tutkimukseni
lopuksi kantaa näiden erilaisten lähestymistapojen hyviin ja huonoihin
puoliin.

Perinteisiä kielennäytteitä kuunnellessa syntyy vaikutelma, että
haastattelija on pyrkinyt mahdollisimman paljon häivyttämään itseään
kuulumattomiin. Kysymykset ovat lyhyitä ja informantin puheeseen ei
reagoida ääntä tuottaen, sillä tämä häritsisi nauhoitusta. Omaa
aineistoani ei kuitenkaan ole kerätty vain kielennäytteiksi, joten ne
sisältävät normaalille keskustelulle tyypillisiä myötäilyjä,
tarkennuksia ja vuoronvaihtoja. Jan Blommaertin ja Jie Dongin mukaan
tätä voi pitää välttämättömänä sisällöllisesti hyvälaatuisen aineiston
keräämiselle. He huomauttavat myös, ettei kaikkia aiheita ole
mahdollista käsitellä kaikissa keskusteluissa, mikä pätee myös
haastatteluihin. [@blommaertEtAl2010a, 46–47].

Osallistuvalla havainnoinnilla tarkoitetaan kyläyhteisössä vietettyä
aikaa, jolloin haastattelujen yhteydessä ja niiden välissä tehtiin
huomioita kylien elämästä ja kielenkäytöstä. Tämä tukee tehtyjä
havaintoja ja auttoi ymmärtämään kontekstia, jossa haastatteluja
tehtiin. Tätä on täydennetty muistiinpanoilla, valokuvilla ja
kartoilla. Tarkoituksena on saada käsitys tutkittavasta yhteisöstä ja
tarkentaa tätä jatkuvasti. Lähtökohtana on edetä yleisestä
havainnoinista yksityiskohtiin [@blommaertEtAl2010a, 29]. Käytännössä
tässä tapauksessa tämä on tarkoittaa esimerkiksi kylässä käytettyjen
kielten tarkkailua. Muistiinpanoihin on kirjattu esimerkiksi hetkiä,
jolloin on kuultu ihmisten keskustelevan tietyllä kielellä, arvioita
heidän iästään, keskustelun aiheesta ja muusta
olennaisesta. Ideaalisesti samoja ihmisiä oppisi tuntemaan pidempänä
aikana ja näitä huomioita voisi yhdistää laajempiin
haastatteluihin. Valitettavasti lyhyillä kenttätyöjaksoilla tämä on
mahdotonta. Samalla silti lyhyelläkin jaksolla syntyy tilanne, jossa
tutkija hahmottaa kenttätyöjakson loppuvaiheessa paremmin yhteisön
tilaa ja osaa näin ollen kiinnittää huomionsa tarkemmin erilaisiin
yksityiskohtiin.

Informantit on valittu niin, että he kaikki asuvat maantieteellisesti
pienellä alueella. Sosiolingvistisille tutkimuksille on tyypillistä,
että aineisto ei välttämättä ole tilastollisesti edustava esimerkiksi
muihin sosiaalitieteisiin verrattuna. [milroyEtAl2003a, 25]. 
Keskittymällä toinen toistensa naapureina asuviin informantteihin
oli mahdollista rajata tutkittavaa aluetta ja potentiaalisten
informanttien määrää. Jäljelle jäi Milroyn ja Gordonin esiin tuoma
ongelma, että ei ole varsinaista keinoa korvata haastatteluista
kieltäytyneitä tai jostain syystä tavoittamatta jääneitä
informantteja. Voin oman aineistoni puolesta sanoa, että toistetuilla
kenttätyömatkoilla näyttää olevan melko helppoa täydentää aineistosta
puuttuvia informantteja, mutta alueella asuvan väestön suuresta
määrästä johtuen oikeasti kattavan otoksen saaminen veisi
huomattavasti enemmän aikaa. Näin jälkikäteen on helppo sanoa, että
esimerkiksi nuoria informantteja olisi tarvittu enemmän. Informanttien
kerääminen tietyltä rajatulta alueelta vaikuttaa metodologisesti
hyvältä mallilta, mutta vaatisi rinnalleen tarkempaa seurantaa eri
ikäluokkien edustumisesta. Kyse on pohjimmiltaan siitä, mitä oikeasti
halutaan tutkia ja mihin tarkoitukseen aineistoa kerätään. Omien
tutkimuskysymysteni kannalta nyt valittu malli vaikuttaa toimivalta ja
kehityskelpoiselta, vaikka onkin vielä osin
puutteellinen. Informanttien valintaa voi verrata New Yorkin
puertoricolaisia käsittelevään tutkimukseen, jossa myös keskityttiin
hyvin pienen korttelin asukkaisiin hyvin tuloksin (Zentella
1997). Olennaisena erona on, että oma aineistoni on kerätty hyvin
lyhyenä aikana, siinä missä Zentellan aineistoa koottiin monta
vuosikymmentä.

Haastattelut on tehty pääosin pareittain tai pienissä ryhmissä. Ne on
useimmiten nauhoitettu ja ajoittain videokuvattu. Kattava
sosiolingvistinen haastattelu kesti noin tunnin, mutta lyhimmät
käyttökelpoiset keskustelutuokiot ovat olleet vain joitain kymmeniä
minuutteja. Kaikkia haastatteluja ei ole nauhoitettu, joten ajoittain
on välttämätöntä tukeutua pelkkien muistiinpanojen varaan. Toisaalta
täytetyt kyselykaavakkeet ja muistiinpanot ovat välttämättömiä
aineiston analyysille, sillä niissä voi olla tilanteeseen liittyviä
yksityiskohtia, jotka selittävät tiettyjä vastauksia.  Haastattelut on
pyritty tekemään Karjalassa karjalaksi ja Komissa komiksi. Osa
haastatteluista on venäjäksi.

Lähtökohtana on, että haastattelut tehdään informanttien
äidinkielellä. Toisaalta äidinkielen käsite on
vähemmistökieliyhteisössä monin tavoin ongelmallinen, sillä se ei
välttämättä ole informantin paras tai luontevin kieli. Ihmisiä
haastatellessa huomaa, että tietyistä aiheista on totuttu puhumaan
vain tietyllä kielellä. Jotkut ovat niin tottuneita puhumaan vain
venäjää, että puheen ohjaaminen vähemmistökieleen tuntuu
keinotekoiselta. Tällöin kielen valinta voi samalla rajata
keskusteluaihetta tai tapaa käsitellä sitä. Mielestäni ei voi
yksiselitteisesti sanoa, että tietyn kielen valitseminen
haastattelukieleksi olisi missään tilanteessa itsestään
selvää. Komissa tehdyille haastatteluille on tyypillistä, että
komilaiset opiskelijat ohjaavat informanttia puhumaan komia. Ajoittain
oma läsnäoloni ohjasi kielivalintaa komiksi, sillä informantit olivat
ajoittain käsityksessä, etten osaa venäjää. Kielentutkimuksen ja
antropologian piirissä on käyty jo varhain keskustelua ja väittelyä
tarpeesta osata tutkittavia kieliä hyvin (Mead 1930, Lowie
1940). Omasta mielestäni tämä on täysin välttämätön lähtökohta, ja
tutkijan tulisikin pyrkiä osaamaan kaikkia yhteisössä käytettyjä
kieliä vapaaseen keskusteluun riittävällä tasolla. Itse koin kesän
2012 kenttätöissä usein ongelmalliseksi heikon venäjän taitoni, joka
tosin viimeisen vuoden aikana jo on alkanut saavuttaa kenttätöissä
tarvittavaa tasoa. Tutkijan pitäisi pystyä osallistumaan
keskustelutilanteisiin, jollainen haastattelukin lähtökohtaisesti on,
kaikilla tutkittujen henkilöiden tässä tilanteessa hyödyntämillä
kielillä. Olkoonkin, että ulkomaalaisen tutkijan taito ja repertuaati
jää väistämättä natiivipuhujia heikommaksi.

### Aineiston arkistointitapa ja eettiset kysymykset

Aineisto on arkistoitu Microsoft Access-ohjelmalla tehtyyn
tietokantaan. Sen rakenne on yksinkertainen ja noudattelee
pääpiirteissään viime vuosikymmenellä kehittyneitä konventioita kieltä
dokumentoivien aineistojen metadatan suhteen (esimerkkinä katso
Himmelmann 2006: 11–12; Thieberger 2010: 145–146). Tämä tarkoittaa,
että tietokannassa on muun muassa perustiedot informanteista ja
yksittäisistä haastattelusessioista sekä henkilöistä, jotka ovat
olleet läsnä missäkin haastattelussa. Näin on mahdollista eritellä,
millaisia aineistoja eri informanteista on ja milloin nämä on
kerätty. Tällä on haluttu varmistaa, että tulevaisuudessakin on
mahdollista identifioida nauhoituksista yksittäisiä puhujia ja
lähestyä aineistoa uusien tutkimuskysymysten kanssa.

Erillisen tietokannan rakentaminen oli välttämätöntä sen takia, että
halusin tietojen olevan loogisesti ja yksinkertaisesti nähtävissä,
mutta samalla kytkettyinä erilaisiin tauluihin tietyistä kysymyksistä
ja teemoista. Nyt tiedot esimerkiksi domeeneista tai kielen
oppimisesta on jäsennelty omiin tauluihinsa ja yhdistetty yksittäisiin
informantteihin heidät yksilöivillä numeroilla. Olen pyrkinyt pitämään
rakenteen yksinkertaisena ja läpinäkyvänä, jotta aineistot olisi
mahdollista siirtää tarpeen tullen toisiin ympäristöihin. Lähtökohtana
mallille on, että jokaisen informantin perustietoihin on kytkettävissä
eri haastattelusessioita ja näihin liittyviä tiedostoja. Näin on
helppo saada yksityiskohtainen kuva siitä, mihin
haastattelutilanteeseen mikäkin tiedosto ja lopulta tiedonanto
kytkeytyy.

Olen kantanut huolta informanttien anonymiteetin säilymisestä. Tähän
on päästy muuttamalla heidän syntymävuosiaan. Analyysini kannalta ei
ole oleellista, onko informantti syntynyt esimerkiksi vuonna 1931 vai
1934, joten tällaisia yksityiskohtia on muokattu niin, etteivät ne
vastaa oikeasti haastateltujen henkilöiden ikiä. Lukija voi seurata
informanttien numeroinnin kautta kuka on vastannut mitenkin, mutta
kuuluu asiaan, etteivät eri tilastojen vuosiluvut täsmää. Muuten
kasvaa vaara, että informantit pystyisi tunnistamaanTutkimusta on
tehty useiden kilometrien kokoisella alueella näissä kahdessa kylässä,
joten ei ole yksityiskohtaisesti jäljitettävissä missä informantit
tarkalleen asuvat. Yksittäiset informantit voivat luonnollisesti
tunnistaa omat vastauksensa siteeratuista esimerkeistä, mutta
tavoitteenani on ollut valita otteita, jotka eivät paljasta
informantin henkilöllisyyttä. Tarpeen vaatiessa nimiä ja muita
henkilötietoja on sensuroitu. Myös käsittelemieni kielellisten
verkostojen yksityiskohtia on manipuloitu informanttien anonymiteetin
säilyttämiseksi. Tutkimuksellisena tavoitteenani tietysti on, että
havainnoimani mallit ja esittämäni väitteet olisivat päteviä nyt
tutkitun alueen ulkopuolellakin, mikä myös tukee informanttien ja
tarkan tutkimuskohteen loitontamista.

Tietokantaan lisätyiltä informanteilta on saatu lupa aineiston
arkistointiin ja käyttöön. Aiheen henkilökohtaisuudesta johtuen
alkuperäisaineistoa ei voi laittaa vapaasti saataville, mutta ei ole
mitään esteitä yksittäisten osien hyödyntämiselle esimerkiksi
paikallismurteita tutkittaessa. Erityisesti kansanperinnettä
käsittelevät haastattelut sisältävät pitkiä ja rikkaita
narratiiveja. Aineisto tullaan arkistoimaan muun muassa Kotukseen ja
sen käytöstä kiinnostuneet voivat ottaa yhteyttä tämän työn
kirjoittajaan.

Esittämissäni sitaateissa haastattelijan puheenvuorot on merkitty
lihavoidulla tekstillä. Komiksi ja karjalaksi olevat litteroidut
näytteet on tehty karkealla suomalais-ugrilaisella transkriptiolla,
mutta venäjässä on käytetty kyrillistä ortografiaa. Rivit on numeroitu
ja tauot merkitty vinoviivoilla.

### Informantit

Informantit jakautuivat iältään taulukon X kuvaamalla tavalla. Otosta
voi pitää hyvänä 1920–1960-luvuilla syntyneiden osalta, mutta tätä
nuoremmista tietoa on valitettavan vähän. Aineistossa on vain
yksittäisiä informantteja, jotka ovat syntyneet 1970-luvun
jälkeen. Tästäkin ryhmästä voi silti saada tietoa epäsuorasti, sillä
nyt haastateltujen informanttien lapset ja lapsenlapset ovat syntyneet
juuri näillä vuosikymmenillä. Informanttien vähäisyys nuoremmissa
ikäryhmissä ei tarkoita sitä, ettei näissä yhteisöissä olisi nuoria
asukkaita.

Informanttien sukupuolijakauma on siten epätasainen, että naisia on
molempien kylien aineistossa huomattavasti miehiä enemmän. Koigortin
aineistossa naisten osuus on jopa kaksi kolmannesta. Yksi selitys
tälle on miesten varhainen kuolinikä Venäjällä, mikä kasvattaa naisten
osuutta iäkkäämmissä kohorteissa.

Tuuksa: Informantteja 55
Miehiä: 23, naisia: 32
Koigort: Informantteja 42
Miehiä: 12, naisia 30

Sekä Tuuksesta että Koigortista on olemassa kahdenlaisia
informantteja, joita kutsun tässä primaarisiksi ja sekundaarisiksi
riippuen siitä, ovatko heidän haastattelunsa kattavia vai ainoastaan
nopeita kohtaamisia. Sisällön puolesta tätä jakoa ei ole aina helppo
tehdä. Aina olisi ollut tarpeellista kysyä tarkennuksia tai
lisäkysymyksiä. Toisaalta jopa hyvin lyhyet haastattelut saattavat
olla sisällöllisesti erittäin rikkaita, joten niiden ottaminen mukaan
tarkasteluun on tärkeää. Haastatteluja ei ole sinällään mahdollista
jakaa huonoihin ja hyviin, sillä jokainen haastattelu saattaa
paljastaa joitain tärkeitä yksityiskohtia (Blommaert & Jie 2010:
56). Jonkinlainen jako on ollut mahdollinen tehdä sen mukaan, kuinka
kattavasti siinä käsiteltiin kyselykaavakkeella kerättäviksi
tarkoitettuja aiheita. Muutaman minuutin mittainen keskustelu ei
mitenkään voi olla lähteenä samanarvoinen tai rikas kuin useamman
tunnin yksityiskohtainen haastattelu.

Erilaisia tavattuja henkilöitä on tietokannassani Tuuksesta 119
kappaletta ja Koigortista 76. Näistä kattavasti haastateltuja
primaarisia informantteja ovat kaikki edellisen sivun taulukkoon X
listatut. Melko yhtenevästä informanttien määrästä huolimatta
aineistot eroavat toisiltaan paljon, sillä erilaisten
haastattelutyyppien osuudet ovat erilaisia. Tuuksen informanteista
lähes jokaisen kanssa on tehty sosiolingvistinen haastattelu, ja
tällaisia onkin yhteensä 40 kappaletta. Ainoastaan kolme haastattelua
on sisällöltään ensisijaisesti etnografisia tai
kansatieteellisiä. Tämä lisäksi sosiolingvististen haastattelujen
yhteydessä on kerätty välillä paikannimistöä, mikä ei sinällään ole
häirinnyt kielisosiologisen aineiston saamista. Koigortin
haastatteluista 20 on sosiolingvistisiä, 16 etnografisia sekä 5 hyvin
vahvasti näiden kahden kyselytyypin kesken sekoittuneita. Käytännössä
molempien haastattelujen elementtejä on lähes jokaisessa
haastattelussa. Näiden ohella Tuuksesta on kymmeniä pääosin
paikannimistöä käsitteleviä haastatteluja, joiden ohessa on
satunnaisesti myös sosiolingvistisesti mielenkiintoista
materiaalia. Tämä jako näkyy tutkittaessa esimerkiksi domeeneja, sillä
Koigortissa kattavasti haastateltuja informantteja on
vähemmän. Toisaalta Koigortin yhteisön historia on nyt tutkittu
Tuuksea paremmin.

Varsinaisten informanttien lisäksi olen pitänyt listattuna
potentiaalisten informanttien ryhmää. Kyseessä ovat ihmiset, joista
meillä on erilaisia toisen käden tietoja, mutta joita ei erilaisista
syistä vielä voitu haastatella. Molemmissa kohteissa on kymmeniä
tällaisia informantteja. Tämä korostaa sitä, että viikon tai kahden
mittaisiin kenttätyöjaksoihin perustuva tutkimus on parhaimmillaankin
keskeneräinen työ, jossa on vasta raapaistu paikallisten sosiaalisten
verkostojen pintaa. Koigortista on vähemmän löytämättömiä
informantteja, mikä selittyy sillä, että kesällä 2013 Tuuksessa
haastateltiin suuri osuus edellisenä kesänä paikallistetuista
henkilöistä.
 
Ikäjakauma on melko samanlainen molemmissa
tutkimuskohteissa. Painopiste on haastatteluhetkellä 50–80-vuotiassa
henkilöissä. Ennen työskentelyä ei erikseen suunniteltu tietynlaisen
otoksen keräämistä, sillä aiempi kokemus kenttätöistä on osoittanut,
ettei informantteja ole välttämättä varaa tai syytä
valikoida. Molemmissa kohteissa saatu jakauma selittyy mielestäni
pääosin sillä, että näissä yhteisöissä tätä ikäluokkaa edustavia
vähemmistökielen puhujia löytyy helpoiten. Noudatettiin esimerkiksi
Lesley Milroyn suosittelemaa metodia lumipallometodia (Milroy 1987),
jossa yhden informantin tuttavaverkoston kautta löydetään uusia
haastateltavia. On vaarana, että menetelmä johdattelee samanikäisten
informanttien luo, sillä ihmisten naapurit ja muut tuttavat voivat
usein olla samasta ikäluokasta. Toisaalta lähes kaikilla
informanteilla oli lapsia, mikä tarjosi yhden väylän nuorempien
kielenoppaiden luo. Näin tehtiin, ja erityisesti Tuuksen aineistosta
tulivat esiin eri perheiden sisäiset kielenkäytön mallit, mistä on
nähtävissä Koigortistakin useita yksityiskohtia.
