# Metodit

## Aiempi tutkimus

### Kielellinen uhanalaistuminen tutkimuskohteena

Nykyään kielitieteessä on kiinnitetty kasvavaa huomiota kielten
uhanalaistumiseen. Tiedetään, että kielenvaihtoa on tapahtunut eri
aikoina, mutta 1900-luvun jälkipuolella käynnistynyt kielten
massakuolema on selkeästi oman aikamme ilmiö. Toisaalta jo
varhaisimpien kenttätyön tekijöiden käsitykseen kuului tutkittavien
kielien uhanalaisuus. Tällä on tutkimustradition alusta asti
perusteltu tarvetta kerätä nopeasti uutta aineistoa. Varsinaisella
kielenvaihdon tutkimisella on nuoremmat perinteet. Tärkeitä
klassikkotutkimuksia ovat esimerkiksi Susan Galin kuvaus Itävallan
unkarilaisista (1979) tai Nancy Dorianin kuvaus gaelin kuolemasta
Skotlannissa (1981). Tuolloin alkoi myös kehittyä teoreettista pohjaa
aiheen tarkastelulle, erityisesti Joshua Fishmanin kytkettyä
kielenvaihdon Fergusonin varhaisempaan diglossian käsitteeseen
(Fishman 1967). Silti esimerkiksi Nancy Dorianin tutkimusta edelsivät
jo 60-luvulla aloitetut kenttätyöt, joten eri tutkimuksia ei voi
sijoittaa vain ilmestymisvuoden perusteella kronologiseeen
järjestykseen. Joshua Fishman on lähestynyt aihetta nimenomaan
sosiologian ja sosiaalipsykologian kautta eikä samoihin aikoihin muun
sosiolingvistiikan puolella kehittyneen variaatiotutkimuksen
perspektiivistä. Fishmanin tutkimusparadigma tunnetaankin usein
termillä sociology of language. Oma tapani tarkastella kielenvaihtoa
on lähempänä juuri Fishmanin mallia, jossa keskitytään enemmän
kielenvaihdon yhteisölliseen puoleen kuin kielten rakenteeseen.

Kielenvaihto alkoi saada enemmän huomiota Language-lehden vuoden 1992
erikoisnumeron myötä, jossa esimerkiksi Michael Krauss ja Ken Hale
ottivat esiin ilmiön katastrofaalisen laajuuden. Ei kuitenkaan vaikuta
siltä, että tämä olisi johtanut välittömästi tutkimuksen määrän
kasvuun. Muun muassa hausan kieltä tutkinut Paul Newman piti syksyllä
2013 Lontoossa SOAS:issa luennon, jossa hän kiinnitti huomiota
1990-luvun vilkkaaseen keskusteluun kielellisestä uhanalaistumisesta,
mikä ei silti useinkaan ollut vielä vuosikymmenen lopulla
realisoitunut konkreettisena työnä1. Erityisesti 2000-luvulla on
ilmestynyt teoksia, joissa tarkastellaan laajemmin vertaillen
kielenvaihtoa eri alueilla, useimmiten juuri yksittäisten
tapauskuvausten kautta (Brenzinger 2007; Batibo 2005; Grenoble &
Whaley 1998; Florey 2010; Hidalgo 2010). Oma vaikutelmani on, että
erityisesti viime vuosina uusien artikkelien määrä on kasvanut
räjähdysmäisesti. Silti laajempia pitkäaikaistutkimukseen perustuvia
monografioita on ilmestynyt vain vähän, ainakin niitä on vaikea
löytää. Ajoittain näkee viitattavan Pohjois-Amerikassa tehtyihin
kiinnostaviin väitöskirjoihin, mutta usein ne eivät ole helposti
saatavilla Suomessa. Kielellisen uhanalaistumisen syiden tutkimisen
ohella on 2000-luvulla kehittynyt huonosti tunnettuja kieliä
dokumentoiva tutkimusparadigma, osittain juuri lingvistien reaktiona
tähän (Himmelmann 2006). Omasta mielestäni olisi ensiarvoisen tärkeää
pyrkiä kuvaamaan myös niitä erilaisia tapoja, joilla kielet ovat
uhanalaistuneet. Ainoastaan näin on mahdollista luoda pohjaa oikealle
kielten revitalisaatiolle ja ymmärtää, millaista variaatiota
kielenvaihdon etenemisessä oikeasti on.

Kritiikkiä sosiolingvistinen tutkimus on saanut myös Joshua
Fishmanilta, joka vuonna 1991 esitti sosiolingvistiikan edenneen
keski-iän kriisiin, johon liittyi olennaisesti liiallinen
keskittyminen kielensisäisiin ilmiöihin yhteiskunnallisen tutkimuksen
ollessa lähinnä kursorisessa roolissa. Erityisesti Fishman moitti
sosiolingvistien perehtymättömyyttä sosiologiseen tutkimukseen ja
teoriaan – ratkaisu, johon Fishmanin mukaan myös sosiologit ovat
päätyneet suhteessa kielitieteeseen (1991: 130–131).

### Suomalais-ugrilaiset kielet uhanalaisina kielinä

Muiden uhanalaisten kielten ohella myös suomalais-ugrilaisten kielten
uhanalaistumista on tutkittu. Laajasti tiettyjä aiheita tutkineina voi
mainita karjalaa tutkineen Anneli Sarhimaan (1999), udmurttia
tutkineen Zsuzsanna Salánkin ja Kuolan niemimaan saamelaisia
käsitelleen Elisabeth Schellerin. Erilaista tutkimusta on tehty
paljon. Esimerkiksi Magdolna Kovács on tutkinut suomalaisten ja
unkarilaisten siirtolaisväestöjen koodinvaihtoa Australiassa
(2001). Riho Grünthal on tarkastelut kielisosiologisesta näkökulmasta
vepsän ja ersän kieliä (2011; 2009). Annika Pasanen on tutkinut
inarinsaamen ja karjalan revitalisaatiota (2003) ja ollut vuosia
mukana käytännön revitalisaatiotyössä. Tutkimusta tehdään eri
puolilla, ja jo Helsingissä tutkimuksien määrä on suuri. Esimerkiksi
puhutun udmurtin kielen variantteja tutkii Svetlana Jedygarova, Outi
Tánczos tutkii lehtiteksteissä esiintyviä vähemmistökieliin liittyviä
diskursseja ja erityisesti kielipolitiikan perspektiivistä
suomalais-ugrilaisia kieliä käsittelee pian valmistuvassa
väitöskirjassaan Konstantin Zamyatin. Muualla työtä tekevät tälläkin
hetkellä erilaisista lähtökohdista lukuisat nuoret tutkijat kuten
Aleksandr Zamyatin, Tatjana Jefremova, Larisa Shirobokova, Jelena
Semenchina ja Csilla Horváth. Tutkimuksen tulevaisuus näyttää
valoisalta, mutta vastaamattomia kysymyksiä on paljon. Mitkä ovat
parhaita tapoja kerätä aineistoa 2000-luvun Venäjällä? Olemmeko
reagoineet riittävästi uuteen nauhoitusteknologiaan ja muihin viime
vuosina kehitettyihin työvälineisiin? Kuinka pystyisimme kuvaamaan
suurten ja varioivien kieliyhteisöjen tilannetta vertailukelpoisella
tavalla? Jaammeko riittävästi aineistoamme, ja välittyykö tieto
metodologisista kokeiluista tai ongelmista maasta tai edes
yliopistosta toiseen? Väittäisin nimittäin yhä, ettemme tiedä
kovinkaan paljoa varmaa Venäjällä puhuttujen uralilaisten kielten
nykytilanteesta. Tarvitaan pitkäaikaistutkimukseen ja
yksityiskohtaisesti analysoituun laajaan aineistoon perustuvaa
tutkimusta.

Jos halutaan tarkastella uralilaisten kielten kielisosiologista
tilannetta, tai tämän tiedon puutteessa edes sen yhteiskunnallisia
lähtökohtia, muihin maailman kielioloihin verraten, on niillä muutamia
hyvin leimallisia piirteitä. Yksi tällainen on koko Venäjän
demografinen kehitys, jolle on ominaista maaseudun autioituminen sekä
erittäin pieni syntyvyys. Maaseudun murros tapahtui
suunnitelmatalouden aikana erittäin nopeasti. Vaikka tuloksena ei
välttämättä ollutkaan alueiden modernisoituminen, aiheutti se
kuitenkin maaseudun haja-asutusalueiden väestön keskittymisen entistä
tiiviimpiin asutuskeskuksiin. Mielestäni merkittävänä omalaatuisuutena
voi pitää myös Euroopan-puoleisen pohjoisen Venäjän suhteellisen
korkeaa väestöntiheyttä, joka on silti niin pieni, että yksittäiset
kyläyhteisöt ovat jokseenkin erillään toisistaan. Siperian tai
Pohjois-Amerikan vastaavilla leveysasteilla väestömäärä on selkeästi
pienempi ja harvempi, populaatioiden ollessa tällöin myös
huomattavasti pienempiä.

Verrattaessa muualla maailmassa tehtyihin ennusteisiin (katso
esimerkiksi Krauss 1998 Pohjois-Amerikasta, Batibo 2005 Afrikasta)
ovat suuremmat uralilaiset kielet kuten komi, udmurtti ja mari
ilmeisesti melko elinvoimaisia. Tilastojen perusteella väestömäärä ei
ole kasvanut oletetulla tavalla (Lallukka 2008), mikä ei silti ole
mitenkään ainutlaatuista. Esimerkiksi ketšuan kielen puhujamäärä on
tähän päivään asti kasvanut, vaikka paikallistasolla kielen tilanne
voi olla hyvinkin huono ja assimilaatio espanjaan nopeaa (Adelaar
2007: 15). Suuria kieliä on uhanalaistunut aiemminkin erittäin
nopeasti, mistä tunnettuja esimerkkejä ovat bretoni ja
navaho. Molempien puhujamäärät olivat hyvin korkeita vielä joitain
sukupolvia sitten, mutta nyt kieliä oppivia lapsia on verrattain
vähän. (Krauss 1992: 7). Ei pidä unohtaa, että keskisuuret uralilaiset
kielet ovat ajoittaisista positiivisista signaaleista huolimatta hyvin
vaarantuneita. Suomalais-ugrilaisten kielten nykytilanteesta voi
sanoa, että kielenvaihto on alkanut suurimpienkin Venäjän
suomalais-ugrilaisten kielen parissa, mutta se ei välttämättä ole
ulottunut kaikille kielten puhuma-alueille ja osa vähemmistökielisistä
paikallisyhteisöistä vaikuttaa hyvin elinvoimaisilta. Lukuisten
kielten siirtyminen lapsille on kuitenkin jo pysähtynyt (Pasanen 2008:
61).

Viime vuosina sosiolingvististä tutkimusta ja uutta aineistoa on
tuotettu muun muassa EU-rahoitteisen ELDIA-projektin puitteissa, mutta
unkaria lukuun ottamatta suuret suomen etäsukukielet jäävät pois sen
piiristä. Toki ELDIA tuottaa tietoa myös esimerkiksi Romanian ja
Slovenian suomalais-ugrilaisista kielivähemmistöistä, mutta
kielenvaihdon konteksti on silti hyvin erilainen kuin Venäjän
sukukielten parissa. Olen itse kirjoittanut tätä seminaaritutkielmaa
MinorEuRus -tutkimushankkeen puitteissa, jonka tavoitteena on tuottaa
vertailevaa tietoa Euroopan ja Venäjän kielivähemmistöistä. Projektin
yhtenä konkreettisena tuloksena on jo syntynyt Annika Pasasen, Janne
Saarikiven ja Konstantin Zamyatinin kirja Как и зачем сохранять языки
народов России (Miten ja miksi säilyttää Venäjän kansojen kieliä)
(2012), joka on ensimmäinen venäjäksi tehty kielen revitalisaatiosta
kertova perusteos. Koko kielikunnan tilan kartoittamisen kannalta
ELDIA ja MinorEuRus ovat molemmat hyvin paljon uutta tietoa tuottavia
tutkimushankkeita.

### Sosiolingvistisen tutkimuksen painotuksista

Sosiolingvistiikkaa (sociolinguistics) on tieteenalana määritelty
siten, että kyseessä on kielen ja yhteiskunnan suhteen tutkimus, jonka
tavoitteena on näiden suhteiden vaikutus kielen
rakenteeseen. Kielisosiologia (sociology of language) puolestaan
pyrkisi kuvaamaan enemmän yhteisön rakennetta kielen kautta (Paunonen
2009; Chambers 1995: 11). Jako ei mielestäni ole täysin
selvä. Toisaalta esimerkiksi Heikki Paunonen on korostanut
kielivähemmistöjen kielenkäytön tutkimusta nimenomaan kielisosiologian
nykyhetken haasteena (Paunonen 2009: 562). Käytännössä tällaistakin
tutkimusta kutsutaan usein lähtökohtaisesti sosiolingvistiikaksi. Tämä
sosiolingvistiikan assosioituminen variaationtutkimukseen on
mahdollisesti johtanut tämän tutkimusmetodin korostumiseen. Tällöin
tutkitaan kielessä itsessään olevaa variaatiota, joka voi olla
esimerkiksi fonologista, morfologista tai leksikaalista
vaihtelua. Lähtökohtana on ajatus, että tämä variaatio on erilaisiin
yhteiskunnallisiin muuttujiin sidottua eikä
sattumanvaraista. Vuosikymmenten aikana painotetut tarkastelutavat
ovat silti muuttuneet. Penelope Eckertin mukaan uusimmalle
sosiolingvistiselle ajattelulle on tyypillistä, että varioivat
kielelliset resurssit eivät itsessään heijastele sosiaalisia
merkityksiä, vaan niitä käytetään aktiivisesti näiden luomiseen ja
yhteiskunnallisen muutoksen ylläpitämiseen (Eckert 2012).

Kielenvaihdon tutkimus on nähdäkseni silti hieman poikkeuksellisessa
asemassa muun sosiolingvistisen tutkimuksen
keskellä. Variaationtutkimus on tässäkin yleinen työkalu, mutta
nähdäkseni tämä on juuri sosiolingvistiikan eikä kielisosiologian
metodi. Ehkä tutkittavaksi variaabeliksi voisi ymmärtää kielen
siirtymisen sukupolvelta toiselle tai erilaisten
kielenkäyttötilanteiden kielivalinnat. Mutta tällöinkään tarkasteltu
muuttuja ei olisi enää kielen järjestelmän sisäinen muuttuja, vaan
jotain yhteiskunnallisempaa, sosiaalisempaa. Näin ollen kielenvaihdon
tutkimuksen metodologiset valinnat voivat välttämättä joutua hyvin
kauas perinteisimmästä sosiolingvistiikasta sekä puhtaasta
kielitieteestä, mikä ehkä on saanut monia tutkijoita pysyttelemään
kysymyksen selkeimmin kielellisessä osuudessa.

Toinen kielenvaihdon tutkimusta tutkimusta tarkastellessa syntyvä
vaikutelma on sellainen, että eniten huomiota saavat kaikista
uhanalaisimmat kielet. Niiden tutkimus on myös kansainvälisesti
parhaiten tuettua ja eri rahoittajien huomioimaa (Dobrin et al:
2007). Näin ollen kielenvaihdon tutkimus keskittyy helposti
kielenvaihdon loppupäähän (esimerkiksi Dorian 1972 gaelista, Kulick
1992 taiapista, Roesch 2012 Teksasin elsassista ja Schmidt 1987
dyirbalista). Saatetaan erikseen mainita poikkeuksellisena
tilaisuutena päästä tutkimaan kielenvaihtoa sen alkuvaiheessa
(esimerkiksi ansiokkaasti garifunan kieltä käsittelevä Ravindranath
2009: 2). Tässä mielessä tutkimus suurempien suomalais-ugrilaisten
kielten kielenvaihdosta täyttää aukkoa kielellisen uhanalaistumisen
tutkimuksessa. Aiempi tutkimus on osoittanut, ettei koko vielä kerro
kielen olevan turvattu. Mainittakoon myös, että uhanalaisten
kontaktikielten kuten pidginien ja kreolien tutkimus on usein
marginaalisessa asemassa uhanalaisten kielten tutkimuksessa
(O’Shannessy 2011: 98).

## Metodologiset lähtökohdat

Lähtökohtana tavalleni tutkia kielenvaihtoa on, ettei ilmiön voi
olettaa olevan kausaliteettisuhteessa minkään yksittäisen muuttujan
kanssa. Kielenvaihto tapahtuu eri puolilla maailmaa niin erilaisissa
yhteisöissä, että kielenvaihdon syiden on oltava erilaisissa
yhdistelmissä historiallisia, sosiaalisia, kulttuurisia, poliittisia,
psykologisia ja kielellisiä muuttujia (Maitz 2011: 153). Vaikka
yksittäiset muuttujat korreloisivat esimerkiksi kielenvaihdon
etenemisen kanssa, on tästä pitkä matka oikeasti yksityiskohtaisten ja
varmojen kausaliteettisuhteiden määrittämiseen (katso lisää Oppenheim
2006: 14). Ilmiöiden temporaalinen järjestys on aina otettava
huomioon, mutta on oltava varovainen esitettäessä väitteitä
peräkkäisten tapahtumien kausaliteettisuhteesta. On aina mahdollista,
että asiat vain sattuivat tapahtumaan peräkkäin tai samanaikaisesti
toisistaan riippumattomista syistä (Oppenheim 2006: 15). Karjalassa ja
Komissa on tapahtunut valtaisa yhteiskunnallinen muutos viimeisen
sadan vuoden aikana. Kaikki tapahtumat eivät varmasti liity
kielenvaihtoon. Jos tällaista suhdetta väitetään olevan, on
selitettävä tarkasti tämän taustalle oletettu mekaniikka.

Olen tarkastellut aiemmin kandidaatintutkielmassani eri ikäluokkien
kielenoppimista karjalaisissa kylissä [@partanen2013a, s. 17–20]. Tämä
osoitti kielenoppimisen mallin muuttuneen tasaisesti eri
vuosikymmenillä. Koulu on muuttunut toisen maailmansodan jälkeen
pääasialliseksi ympäristöksi, missä venäjä on omaksuttu. Yhteisö- ja
perhekohtaisesti venäjä on siirtynyt eri vuosikymmenillä myös
kotikieleksi. Tällaisella tarkastelulla on kuitenkin mahdollista
havaita yksityiskohtaisia eroja yhteisöjen välillä. Yleisestä
kielenvaihdon kulusta poikkeavien informanttien syvähaastatteluista on
oletettavasti mahdollista osoittaa syitä, joiden takia heidän
kielenkäyttönsä on muuttunut heidän ikäkohortistaan poikkeavalla
tavalla. Esittelin jo johdannossa yksittäisiä
lähtöhypoteesejä. Oletan, että nuoret osaavat perinteisiä kieliä
vanhempiaan vähemmän. Toisaalta pidän todennäköisenä, että nuoret
ikäryhmät osaavat näitä kieliä erilaisin tavoin. Lukuisat tutkimukset
ovat kuvanneet, että passiivinen kielitaito olisi yleistä
kielenvaihtoa läpikäyvissä yhteisöissä. Silti ei ole juurikaan
tutkimuksia, joissa tarkasteltaisiin mitä tällaisella taidolla
tarkoitetaan ja mitä se merkitsee näissä yhteisöissä. Heillä on
kuitenkin esitetty olevan keskeinen rooli kielen
revitalisaatiossa. (Basham & Fathman 2008: 4–5).

Olen käyttänyt tässä tutkimuksessa kolmea metodia. Nämä ovat
ikäryhmien vertailu sekä domeenien ja sosiaalisten verkostojen
tutkimus. Ikäryhmien vertailu liittyy olennaisesti tutkimuksen
näennäisaikaiseen luonteeseen. Saatavilla on ainoastaan yksi otos,
joten eri-ikäisiä informantteja on skaalattava toisiaan vasten ja
tarkkailtava, voisiko ero ikäluokkien vastauksissa heijastella
muutosta tänä aikana. Näennäisaikaisesta metodista on huomautettu,
että sitä on erityisesti käytetty äänteellisiä muutoksia
tarkasteltaessa. On epäselvää, toimisiko se yhtä hyvin esimerkiksi
leksikaalisten muutosten kohdalla. Aihetta käsitellessään Guy Bailey
korostaa myös metodin tarvitseman suuren ja edustavan otoksen
tärkeyttä. (Bailey 2002). Näin ollen ei ole ollenkaan itsestään
selvää, miten metodin tuloksia on arvioitava omassa
aineistossani. Tämä ei ole kuitenkaan ainoa metodini, ja näitä
yhdistelemällä on toivoakseni mahdollista kytkeä yksittäisten
henkilöiden kanssa tehtyjä haastatteluja toisiinsa, aikaan sekä
tilaan, jossa kielenvaihto on tapahtunut. Ideaalinen malli kytkisi
kaikki informantit toisiinsa erilaisin suhtein, mutta valitettavasti
nyt käytössä oleva aineisto ei salli näin pitkälle vietyä
analyysia. Yhdistän näihin metodeihin yksittäisten informanttien
haastatteluissa esiintyviä narratiiveja, mutten keskity yksinomaan
niihin. Haluan kuitenkin informanttien oman kerronnan ja äänen tulevan
esiin oman analyysini yhteydessä. Tietyssä mielessä näiden
narratiivien ja diskursiivisten käytänteiden hyödyntämistä voi pitää
omana metodinaan, mutta en vie tätä tutkimuksessani kovin pitkälle.

## Domeenien tutkimus

Domeenin käsitteen teki yleisesti tunnetuksi Joshua Fishman. Hänen
mukaansa domeeni tarkoittaa institutionalisoitunutta ympäristöä, jossa
samanlaiset käyttäytymismallit toistuvat. Tällaisten
käyttäytymismallien piiriin kuuluvat myös kielenkäytön valinnat. Näin
domeenit määrittelisivät niiden sisällä tapahtuvia kielellisiä
valintoja. (Fishman 1972). Vastaavaa tutkimustapaa on jo varhain
hyödyntänyt muun muassa gaelin kieltä tutkinut Nancy Dorian
(1981). Domeeneja on myös kritisoitu, ja esimerkiksi Itävallan
unkarilaisia tutkinut Susan Gal ei pidä domeeneja merkityksellisinä
omassa aineistossaan, vaan korostaa yksittäisten suhteiden
(interlocutor) merkitystä kielivalinnan määräytymisessä (Gal 1979:
124–125). Kuitenkin myös Fishman kiinnittää huomiota siihen, että
domeenit voi nähdä yksittäisten henkilöiden tai paikkojen sijasta
yksilöiden välillä olevina rooli-suhteina (Fishman 1972: 250). Tällä
hän tarkoittaa että esimerkiksi äidin ja lapsen domeenien sijasta
tarkasteltaisiin erikseen lapsen äidille ja äidin lapselle puhumaa
kieltä. Myös Nancy Dorian on huomauttanut domeenin (domain) ja
ympäristön (setting) lisäksi puhekumppanin (interlocutor)
tärkeyttä. Näin ollen abstraktimmat domeenit voi purkaa henkilöihin,
jotka niihin osallistuvat, mutta myös konkreettisista henkilöiden
välisistä suhteista voi tiettyjen mallien toistuessa yleistää
domeeneja. Hyödynnän tutkimuksessani mallia, jossa esimerkiksi
perhettä käsitellään yhtenä domeenina, ja sen osallistujia kuten äitiä
ja lapsia tämän domeenin osallistujina. Samoin esimerkiksi kylän
kaupassa on voinut olla vuosikausia sama työntekijä, mutta silti tilaa
voi käsitellä abstraktimpana domeenina kauppa kyläyhteisön
kontekstissa. Oma lähestymistapani on nyt lähempänä Fishmanin
alkuperäistä käsitystä domeenista, mikä johtuu pääasiassa aineiston
suppeudesta. Tieto henkilökohtaisista suhteista ei ole tässä otoksessa
niin laajaa, että siitä voisi tehdä Galin tapaan tarkkoja
johtopäätöksiä laajemmista yhteisössä merkityksellisistä
ryhmistä. Abstraktimpia domeeneja puolestaan on kartoitettu melko
paljon. Tällaisinä ne tuovat tutkimukseen tilallisen ulottuvuuden ja
sitovat kielenvaihdon etenemistä tiettyihin konteksteihin ja
ympäristöihin.

Tärkeä kyselykaavakkeeseen otettu metodologinen uudistus on ollut
kysyä erikseen kielenkäytön muutoksesta eri domeeneissa. Ajatus tähän
on saatu Stanley Liebersonin artikkelista, jossa hän ehdotti tällaisen
tarkastelutavan parantavan kielisosiologisten tutkimusten tuloksia
(Lieberson 1980: 15–16). Tämä on yksi keino saada tietoa kielenvaihdon
ajallisesta ulottuvuudesta, vaikka tiettyjä ongelmia tähänkin malliin
sisältyy. Se voi silti olla ainoa mahdollisuus, jos aiempia
tutkimuksia ei ole tehty samoissa yhteyksissä. Ja vaikka olisikin, ne
eivät välttämättä vastaa sisällöltään nykyisen tutkimuksen tavoitteita
tai vaatimuksia. Aihetta näin käsitellessään Joshua Fishman on
huomauttanut, että informantit saattavat vastata ajoittain tavalla,
jolla he olettavat tutkijan haluavan vastattavan. Nyt valitussa
mallissa tällaisia epävarmuustekijöitä on sekä ennen että nyt
-tyyppisissä vastauksissa. (Fishman 1991: 41–42). Karjalasta ja
Komista on olemassa melko paljon vanhempaa tutkimusta, mutta tämä ei
useinkaan ole keskittynyt kysymyksiin, joihin nyt halutaan vastausta.

Käsittelen tässä tutkimuksessani domeeneja kahdessa ryhmässä, joita
ovat perhe osallistujakohtaisesti tarkasteltuna ja muut
domeenit. Perheellä tarkoitan suoraan sukupolvittain määrittyvää
ryhmää, joka alkaa ideaalisesti isovanhemmista ja jatkuu lasten
lapsiin. Käytännössä aina ei ole tietoa näin monesta
sukupolvesta. Informantti ei välttämättä ole tuntenut isovanhempiaan,
eikä kaikille ole lapsia tai lapsenlapsia. Tähän yhdistyvät puoliso ja
sisarukset, sillä he kuuluvat nähdäkseni tällaiseen traditionaaliseen
sukupolvelta toiselle tapahtuvan kielen transmission piiriin. Olen
soveltanut aineistoon jo kandidaatintutkielmassa käyttämääni
menetelmää, jossa informanttien lasten ja lastenlasten ikiä
vertailemalla on tehty tulkintoja eri vuosikymmenillä lasten oppimista
kielistä. Domeenianalyysi on siten näennäisaikainen metodi, että
eri-ikäisten informanttien katsotaan edustavan eri ajoille tyypillistä
mallia. Vertaamalla informanttien omia jälkeläisiä muihin
informantteihin on mahdollista arvioida domeenianalyysin toimivuutta.

Muita tarkastelemiani domeeneja ovat koti, naapurit, kylä, työ, kauppa
ja koulu. Kyselykaavakkeessa on katettu useampiakin domeeneja, mutta
niihin ei ole saatu riittävästi vastauksia, että niiden
kokonaisvaltaisempi tulkinta olisi mielekästä. Käsittelin osiossa
X. Aineisto tarkemmin haastattelumalleja, joilla domeenianalyysin
aineisto on kerätty. Käyn seuraavaksi läpi domeenien teoreettista
merkitystä domeeni kerrallaan.

Domeeni koti liittyy erikseen tarkastelemaani sukupolvien välillä
tapahtuvaan kielenkäyttöön. Käytännössä tässä on usein tarkasteltu
monia sukupolvia, jotka eivät ole olleet elossa samaan aikaan. Näin
ollen yksittäisen informantin kautta määrittyvä domeeni koti voi olla
hyvin erilainen käsite kuin laajempi ja abstraktimpi sukupolvien
välillä tarkasteltu muutos. Tämän takia vertaankin näiden kahden
perhepiiriin rajoittuvan tarkastelutavan tuloksia. Domeeni koti voi
koostua ydinperhettä laajemmasta ihmisjoukosta, minkä lisäksi siihen
tulee ajan mittaan uusia ihmisiä esimerkiksi lasten puolisoiden
muodossa. Tämä luo asetelman, jossa minkään domeenin ei voi olettaa
olevan lähtökohtaisesti muuttumattomana yksilön eliniän
aikana. Viimeisin analysoimani ryhmä, kyliin muuttaneet karjalaa
osaamattomat, ovat tässä hyvin keskeinen ryhmä. Aiempi tutkimus
viittaa Karjalassa etnisten jännitteiden olevan hyvin matalia, joten
eri etniseen ryhmään kuuluminen ei ole todennäköinen este perheiden
perustamiselle. Näin ollen kyliin muuttaneet muunkieliset ovat sitä
väestönosaa, joka karjalaisiin perheverkostoihin integroituessaan
saattavat muuttaa ydinperheenkin kielenkäyttöä enemmän
venäjänkieliseksi. Toisaalta he saattavat myös assimiloitua
kielellisesti paikalliseen yhteisöön.

Olen itse ottanut perheen tärkeimmäksi tarkastelemakseni domeeniksi,
mutta ottanut huomioon ajatuksen domeenin sisällä olevista henkilöistä
jakamalla perheen yksityiskohtaisesti eri sukupolviin ja
perheenjäseniin seuraten Fishmanin jakoa rooli-suhteisiin. Tarkennan
tätä myöhemmin kielellisten verkostojen kautta. Huomauttaisin myös,
ettei domeenin koti rooli kielenvaihdossa ole täysin selvä. Iiriä
tutkineen Ó Riagáinin mukaan koti voi tietyissä tilanteissa olla
ensimmäinen eikä viimeinen kielenvaihdon domeeni. Hän selittää, että
kotona tehtävät asiat eivät välttämättä ole kovin vuorovaikutteisia,
jolloin heikomminkin kieltä osaavat ihmiset voivat osallistua domeenin
toimiin. (Ó Riagáin 1997: 104). Eräs Intiassa tehty tutkimus viittaisi
taas tilanteeseen, jossa paikallista kieltä käytettäisiin erityisen
paljon perheen parissa, mutta jo tähän läheisesti liittyvät naapurit
ja ystävät olivat vahvasti englanninkielisiä (Parasher 1980). Tutkimus
keskittyi korkeasti koulutettuihin henkilöihin, mikä voi tehdä sen
vertaamisen maaseudun paikallisyhteisöihin vaikeaksi. On myös
kuvauksia, joissa kodin sijasta erilaiset rituaaliset yhteydet ovat
säilyttäneet kieltä kauimmin (Mithun 1989: 244). Esimerkiksi
mainitsemani Teksasin tšekkiläisten hautakiviin kohdistunut tutkimus
käsitteli juuri domeenissa rituaali käytettyä kieltä, jonka muutos ei
välttämättä vastaa ajallisesti yhteisön vernakulaarin muutosta (Cox et
al. 2007: 8). Silti muutos näkyy tässäkin aineistossa. On ollut melko
vaikeaa löytää vastaavia domeeneja hyödyntäneitä tutkimuksia, joissa
tutkimuskohteena olisi vastaavanalainen maatalousyhteisö kuin nyt
tarkastelemani. Domeenien tarkka dynamiikka vaikuttaa silti olevan
hyvi vaihtelevaa ja yhteisökohtaista, mikä osaltaan rohkaisee
tarkastelemaan domeeneja uusissa yhteyksissä.

Domeenit eivät ole stabileeja vaan muuttuvat ihmisen eliniän
aikana. Tämän lisäksi yksilö sosialisoituu niihin eri aikoina. Kenties
kodin näkeminen kaikkein tärkeimpänä domeenina liittyy sen roolin
lapsen ensimmäisenä domeenina. Päiväkoti, koulu, opiskelupaikka, työ –
nämä ovat periaatteessa toinen toisensa jälkeen yksilön elämään
tulevia ympäristöjä. Kielivalinnat yhdessä vaikuttavat myöhemmin
käytössä olevaan kielirepertuaariin. Tutkijoilla ei ole yhtenevää
käsitystä siitä, mikä on kaksikielisyyden kehittymiselle välttämätön
altistumisikä tai onko tällaista ikää edes olemassa (Butler & Hakuta
2006: 127–128). Joka tapauksessa kyky oppia kieltä näyttää heikkenevän
noin 6–7-vuotiasta lähtien 16–17-vuotiaisiin asti (DeKeyser 2004:
500). Tämä tarkoittaa, että kotona, päiväkodissa ja koulussa käytetty
kieli on erityisen tärkeässä roolissa. Olen ottanut tämän huomioon
tarkastelemalla kielenkäyttöä koulua erillään muista domeeneista.

Domeeni naapuri tarkoittaa informantin ympärillä asuvia ihmisiä. On
kyselty erikseen eri naapuritaloissa asuvien henkilöiden etnistä
ryhmää ja kielitaitoa, minkä lisäksi informanttia on pyydetty
arviomaan, mitä kieltä hän pääasiassa käyttää naapureiden kanssa
keskustellessaan. Informantit asuvat pääasiassa samalla alueella,
joten näitä vastauksia yhdistelemällä on mahdollista arvioida
naapuruston kielenkäyttöä ja ihmisten arvioiden koherenttiutta.

Domeeni kylä viittaa tässä naapurustoa laajempaaan
alueeseen. Käytännössä sen voi ajatella viittaavan paikallista
kylänosaa kauemmas, mutta ei välttämättä aivan koko kylään. Kyseessä
on kuitenkin kilometrien mittainen taajama, eikä ole selvää, että
ihmiset liikkuisivat säännöllisesti koko alueella. Olen hyödyntänyt
domeenin kylä määrittelyssä haastatteluissa kysyttyä domeenia, joka
suomeksi kääntyisi ’ulkona’, ’kylillä’ tai ’muut ihmiset’. Itse olen
haastatteluissa muotoillut tämän niin, että mitä kieltä kuulette tai
käytätte eniten tässä raitilla. Karjalaksi on käytetty määritteitä
kuten hierus, hierun uliččoil, komiksi taas ывлаын, сиктын
гуляитiгöн. Tällä on haluttu viitata laajempaan alueeseen kylässä,
mikä ei ole mitenkään yksiselitteistä nykyisten kylien rakennuttua
vanhojen kylien päälle. Tavoitteena tällä on kuitenkin ollut
kartoittaa hieman naapurustoa laajemman alueen kielenkäyttöä ja
kielimaisemaa.

Kauppa puolestaan on julkinen tila, jossa ihmiset asioivat
säännöllisesti. Nyt tutkituissa yhteisöissä jokainen asukas joutuu
hankkimaan ainakin osan käyttämistään tarve-esineistä ja ruoista
ostamalla kyseiset tuotteet kaupasta. Oikeastaan kummassakaan
yhteisössä minkäänlainen pelkän luontaistalouden tila ei ole ollut
läsnä nyt haastateltujen informanttien tai edes heidän isovanhempiensa
elinaikana, vaikka pienviljelyn ja pyynnin osuus onkin pienentynyt
viimeisen sadan vuoden aikana huomattavasti. Kauppa on näin ollen
siten hyvä valinta tarkastelluksi domeeniksi, että kaikki informantit
asioivat täällä ja käytännössä eri naapurustojen kaupat on mahdollista
paikallistaa. Domeenissa kauppa asiakkaan ja myyjän roolit ovat
erotettavissa toisistaan. Fishman korostaa, että tämä nostaa esiin
yksittäisten henkilöiden aseman sekä kuulijana että kuuntelijana. Hän
ehdottaa, että useiden kielten tuottamisessa ja ymmärtämisessä voi
olla eroja erilaisten roolien välillä. (Fishman 1972: 250). Nähdäkseni
tämä on otettava huomioon tarkasteltaessa domeenia kauppa, mutta ei
kuitenkaan vain siinä.

Domeeni työ viittaa jokaisella informantilla eri paikkaan. Tämän takia
tarkastelenkin sitä yksityiskohtaisesti eri ammattiryhmien
kielenkäyttöä vertaillen. Aiemmat yritykseni käsitellä domeenia työ
tällaisen aineiston pohjalta toi esiin käytäntöyhteisöt (communities
of practice) toimivana tarkastelutapana. Penelope Eckertin mukaan
käytäntöyhteisö on ryhmä, joka kokoontuu toistuvasti tietyn yhteisen
toiminnan takia. Tärkeää määrittelylle on toiminnan jatkuvuus ja
yhteinen tarkoitus. Ne ovat paikkoja tiettyjen konventioiden
syntymiselle ja vakiintumiselle, liittynen näin myös kielellisiin
konventioihin. (Eckert 2006: 683). Eckertin määritelmällä esimerkiksi
työpaikka ei välttämättä ole toimintayhteisönä. Tästä huolimatta sen
sisällä olevat pienemmät ryhmät voivat olla. Ben Rampton huomauttaa,
että käytäntöyhteisöjen tutkimus edustaa yhdenlaista modernia
käsitystä puheyhteisöstä, joka pohjautuu erityisesti pienten ryhmien
päivittäisen vuorovaikutuksen tarkasteluun (Rampton 2006: 14–15).

Domeenia koulu on tarkasteltu siten, että erityistä huomiota on
kiinnitetty lasten siellä käyttämään kielen ja opettajien
suhtautumiseen tähän. Koulukieli sinällään on vaihtunut poliittisten
päätösten myötä, mutta on mielenkiintoista tarkastella kuinka tämä
suhtautuu asenteisiin ja käytäntöihin. Esimerkiksi Tove
Skutnabb-Kangas on rinnastanut kielelliset oikeudet ihmisoikeuksiin ja
korostanut koulutuksen merkitystä kielten säilyttämisessä
(2000). Koulutuksesta hänen kanssaan on ollut samoilla linjoilla
Bernard Spolsky, joka on painottanut tämän lisäksi laajemmin
kielipolitiikan merkitystä. Spolskyn tuotannosta nousee esiin tärkeä
huomio, että koululaitoksen merkitystä on tarkasteltava sellaisesta
näkökulmasta, joka huomioi koulun kautta tulleen vaikutuksen kuten
esimerkiksi tietynlaiset kielelliset ideologiat (Spolsky 2002:
140). Koulu itsessään ei välttämättä riitä selittämään
kielenvaihtoa. Saman huomion on tehnyt zapoteekkikieliä tutkimut Mark
Sicoli (Sicoli 2011).

Kielen elinkaari alkaa lähestyä loppuaan silloin, kun kukaan ei enää
käytä sitä missään domeenissa. Uralilaisista kielistä esimerkiksi
metsäenetsin kieli on tällä hetkellä tällaisessa pisteessä
elinkaartaan, sillä Florian Sieglin mukaan sitä ei ole käytetty
joihinkin vuosikymmeniin (Siegl 2013: 56). On lukuisia esimerkkejä
kielistä, jotka säilyvät hyvin kauan yhdessä tietyssä
käyttöympäristössä. Tämä on usein kytköksissä perinteisten
elinkeinojen säilymiseen (esimerkiksi Aikio 1988). Tällainenkin yhden
selkeän domeenin säilyminen vähemmistökielisenä tarkoittaa, että hyvin
moni muu ympäristö on jo hävinnyt. Tämä tarkoittaa, että tietyt
domeenit ovat voineen enemmistökielistyä aiemmin kuin
toiset. Tutkimukseni kannalta on relevanttia etsiä domeenien
muutoksesta tiettyä järjestystä tai mallia, jolla voisi selittää
kuinka nykyinen tilanne on kehittynyt. Molemmissa kylissä on
haastateltu eri-ikäisiä informantteja, ja erojen heidän vastauksissaan
oletetaan heijastelevan tällä aikavälillä tapahtunutta
muutosta. Sosiolingvististen näennäisaikatutkimusten yksi ongelma on,
että informantit ovat saattaneet muuttaa puhetapaansa elämänsä aikana
(Bailey 2002: 320). Näin ollen saatu näyte ei heijastele varhaisempaa
muotoa, vaan pitkän ajan mittaan omaksuttua puhetapaa. Domeenien
tutkimuksessa ongelma ei ole aivan samanlainen, mutta tässä ongelmana
on ihmisten käsityksen muuttuminen tietyissä ympäristöissä
tapahtuneesta kielenkäytöstä. Informanttien muistot vuosikymmeniä
sitten vallinneista kielioloista ovat saattaneet värittyä monien
erilaisten assosiaatioiden kautta, mitä on mahdotonta erottaa
kerätystä aineistosta.

Tällaisia erikseen kyseltäviä kielenkäytön domeeneja on periaatteessa
lukemattomia, mutta lyhyen kenttätyöjakson puitteissa valintoja oli
jollain tavalla rajattava. Valinnat pohjautuivat pitkälti
Vuokkiniemellä vuonna 2004 kysytyissä avokysymyksissä lueteltuihin
domeeneihin (ks. Kuokkala et al. 2004). Näistä avokysymyksistä sai
alustavan listan, jota voi pitää Karjalan kontekstissa
relevanttina. Nyt kysyttyjä domeeneja olivat isovanhemmat, vanhemmat,
sisarukset, puoliso, lapset, lapsenlapset, lapsenlapsenlapset, muut
ihmiset (tuttavat ja ihmiset kylällä yleensä), naapurit, koulu,
kauppa, ulkona / pihalla kuullut/käytetyt kielet, työpäivän aikana
käytetty kieli, juhla, administraatio sekä eläimet. Tämän lisäksi
esitettiin kysymyksiä ajattelun ja unien kielistä, mutta näissä ei
erikseen tarkasteltu ajallista muutosta. Karjalassa kysymyksiä on
esitetty seikkaperäisemmin yksi kerrallaan, siinä missä Komissa niitä
on usein yritetty sisällyttää etnografisempiin
haastatteluihin. Ensimmäinen strategia on nyt jälkikäteen
tarkasteltuna osoittautunut paremmaksi. Ajoittain informantit jättivät
vastaamatta tiettyihin kohtiin, jolloin siirryttiin eteenpäin. Usein
kävi niin, että haastattelu keskeytyi ennen kuin koko kaavaketta
ehdittiin täyttää. Näin ollen domeenit kuten administraatio on jätetty
lopullisen analyysin ulkopuolelle. Aiemmin Vuokkiniemellä (2004) on
kokeiltu tekniikkaa, jossa informantteja on pyydetty luettelemaan
paikkoja, joissa puhuu karjalaa. Mahdollisesti tästä voisi soveltaa
erityyppistä toimivampaa keräysmenetelmää.  Nyt aineiston analyysin
edettyä pidemmälle on selvää, että esimerkiksi uskonnollisista
domeeneista olisi ollut syytä kysyä erikseen. Toisaalta aineistosta
puuttuu isovanhempien sekä eri-ikäisten sisarusten erittely, mistä
varsinkin jälkimmäinen on tällaisissa tutkimuksissa usein käytetty
muuttuja (esim. Dorian 1981; Smith-Christmas & Smakman 2009).

Esitän domeenit informanttien iän mukaan järjestetyissä taulukoissa,
jotka on värikoodattu vastaustyypin mukaan. Haastatteluissa on kysytty
eri henkilöiden osaamia kieliä sekä eri ympäristöissä käytettyjä
kieliä. On vaikea erottaa, onko informantti tarkoittanut vastatessaan
henkilön osaamaa vaihänen kanssaan puhumaansa kieltä. Nämä ovat
väistämättä osin sekaisin aineistossa. On otettava huomioon, että
taulukossa karjalankieliseksi merkitty solu ei varsinkaan nuorempien
ikäryhmien kohdalla tarkoita, että tämä henkilö ei osaisi venäjää. Se
vain kertoo, että informantin mukaan hän itse ei puhu venäjää tämän
kanssa. Taulukkoa luetaan seuraavalla tavalla:

Taulukko 3. Domeenianalyysin lukuohjeet

Taustalla oleva konventio eri kielten merkitsemisestä
kirjainlyhenteillä on saanut mallia Susan Galin tekemistä kaavioista
(Gal 1979: 101). Omassa mallissani on kuitenkin useampi muuttuja
arvioiden kielitaidon suhteen, joten olen värikoodannut vastaukset
selkeyden ja havainnollistavuuden vuoksi. Näin toteutettuna taulukosta
on mahdollista tarkastella eri ikäryhmien välillä olevia eroja
vastauksissa. Se osoittaa yksittäisten henkilöiden poikkeamisia
yleisemmästä mallista, jolloin heidän henkilöhistorioistaan voi etsiä
syitä aineistosta näkyville kielivalinnoille. Valitsemani mallin
suurimpana puutteena näen sen, ettei haastattelukaavakkeeseen
valittujen domeenien määrittely pohjaudu pitkäaikaiseen etnografiseen
työhön tutkituissa yhteisöissä. Jo Joshua Fishman on todennut, että
tietyn yhteisön kielenkäytön domeenien määrittely vaatisi eriaikaisten
sosiaalis-kulttuuristen prosessien tuntemista. (Fishman 1972: 248). On
mahdoton kuvitella, että suomalaiset tutkijat pystyisivät
intuitiivisesti arvioimaan, millaiset sosiaalisen vuorovaikutuksen
tilat ovat tällaisissa yhteisöissä relevantteja.

## Verkostojen analyysi

Domeenien sisällä olevan vuorovaikutteisuuden takia olen kokenut
sosiaaliset verkostot niihin hyvin yhdistyväksi työkaluksi. Aiemmin
muun muassa Anneli Sarhimaa on kehottanut tutkijoita hyödyntämään
sosiaalisten verkostojen analyysia suomalais-ugrilaisten kielten
tutkimuksen parissa (Sarhimaa 2009). Verkostoanalyysi on alun perin
sosiologian metodi. Se on omaksuttu myöhemmin monien eri tieteenalojen
käyttöön, ja termillä verkostoanalyysi viitataankin nykyään suureen
määrään erilaisia tutkimustapoja (Sarhimaa 2009:
162). Sosiolingvistisessä tutkimuksessa se on osoittautunut
hyödylliseksi työkaluksi perinteisten muuttujien kuten iän tai
sukupuolen rinnalla (Matsumoto 2010). Guernseyn saarella puhuttavaa
dgèrnésiaisin kieltä tutkinut Julia Sallabank on varoittanut, että
sosiaalisten verkostojen hyödyntämisessä on oltava tarkkana
sovellettaessa metodia käyttämälläni lumipallometodilla kerättyyn
aineistoon (Sallabank 2010: 188). On vaarana, että tällainen aineisto
korostaa vähemmistökieltä erityisen paljon käyttäviä henkilöitä.

Sosiolingvistiikkaan verkostoanalyysia toi eritoten Lesley Milroy
1970-luvulla tekemillään tutkimuksilla Belfastissa. Hän osoitti
tiiviiden sosiaalisten verkostojen korreloivan yhteisössä esiintyvien
murrepiirteiden kanssa, mutta nimenomaan heikkojen yhteyksien olevan
vastuussa uusien innovaatioiden leviämisestä. Vahvat verkostot
puolestaan säilyttävät samoja muotoja. (Milroy 1987.) Englantiin
muuttaneita kiinalaisia tutkinut Li Wei on esittänyt, että
verkostoanalyysin avulla on mahdollista kytkeä aineistossa esiintyvää
variaatiota laajempaan yhteiskunnalliseen kontekstiin (Li Wei 1994:
2). Erityisesti Kazuko Matsumoton tutkimukset Palaun saarella (2010)
ovat olleet merkityksellisiä, sillä hän korostaa tarvetta soveltaa
verkostoanalyysiä paikallista kontekstia huomioiden ja juuri siinä
olennaisia muuttujia valiten (Matsumoto 2010). Myös Anneli Sarhimaa on
nostanut tämän esiin (Sarhimaa 2009: 166–167).  Matsumoto korostaa,
ettei verkostoanalyysilla ole mahdollista rekonstruoida menneisyyden
sosiaalisia verkostoja. Tämän ohella sosiaaliset verkostot voivat olla
vähemmän tärkeä muuttuja kielenvaihdon tilanteissa, joissa epäsuorasti
pakotetaan käyttämään toista kieltä institutionalisoitujen tai
auktoritaaristen voimien kautta. (Matsumoto 2010: 161). Nähdäkseni
tämä on syytä pitää mielessä tutkittaessa tilannetta Karjalassa tai
Komissa, sillä monet kielenvaihtoon vaikuttaneet sosiaaliset verkostot
ovat voineet jo kadota esimerkiksi vieraskielisen väestön muutettua
suurissa määrissä pois Neuvostoliiton hajoamisen jälkeen.

Uralilaisten kielten parissa muun muassa Mari Mets on soveltanut
vastaavaa metodia tutkiessaan eteläviron morfologista vaihtelua (Mets
2010, 2012). Nina Kunnas on käyttänyt vienankarjalaa käsittelevässä
tutkimuksessaan sosiaalisia verkostoja yhtenä työkaluna, mutta hänen
tulostensa perusteella verkosto ei selitä variaatiota yksilöiden
välillä, vaan tässä selittäviä ovat kielelliset asenteet ja
kielellinen lojaalius (Kunnas 2007: 309–310). Anneli Sarhimaan ja
Niina Kunnaan aiemman tutkimuksen mukaan karjalan kielen nykyinen
sosiolingvistinen variaatio ei olisi kytköksissä koko yhteisöön vaan
yksittäisiin henkilöihin (Sarhimaa 1995: 316; Kunnas 2007:
315). Heidän tutkimuksensa edustaa perinteistä variaationtutkimusta,
mutta voi silti kysyä, onko väite validi myös kieltä säilyttäneiden
tai vaihtaneiden informanttien välillä. Mielestäni onkin
merkillepantavaa, että verkostoanalyysin sovellukset ovat olleet
ensisijaisesti perinteisen variationistisen sosiolingvistiikan
puolella, kuten esimerkiksi juuri mainitsemissani Kunnaksen ja Metsin
tutkimuksissa. Tällöin tarkastellut muuttujat ovat olleet erityisesti
äänteellisiä ja morfologisia variaabeleja. Varsinaisen kielenvaihdon
tutkimuksen puolella verkostoanalyysin sovellutukset ovat olleet
harvinaisempia, vaikka niitä löytyykin jo jonkin verran. Varhaisena
esimerkkinä verkostoanalyysista tällaisessa tutkimuksessa voi
mielestäni pitää jo Marjut Aikion tutkimusta Saamelaiset kielenvaihdon
kierteessä (1988), sillä hänen metodologinen lähtökohtansa oli
tarkastella eri saamelaiskylien asukkaiden keskinäistä kielenkäyttöä
hyvin yksityiskohtaisesti ja pitkältä ajalta.

Olen näiden tutkijoiden innoittamana alkanut itse joitain vuosia
sitten kerätä tällaista analyysia mahdollistavaa aineistoa, mutta
käytännössä työ on vielä pahasti kesken. Tarve tällaisen aineiston
keräämiselle syntyi kokemuksestani, että toisistaan irrallaan tehdyt
haastattelut menettävän suuren osan analysointimahdollisuuksistaan,
jos informanttien keskinäiset suhteet jätetään huomiotta. Sovellan
kielellisiä verkostoja hyödyntävää tutkimusmallia jo tässä työssäni,
vaikka käytännössä tämän menetelmän kaikkia mahdollisuuksia ei voikaan
ottaa huomioon näin suppeassa käsittelyssä. Verkostoanalyysin
käyttäminen vaatisi hyvin laajan ja yhtenäisen otoksen, jotta
analyysin taustalla olevat matemaattiset mallit oikeasti
toimisivat. Tämä edellyttäisi kymmenien erityyppisten suhteiden
kartoittamista informanttien välillä, vaikka tätä onkin pidetty hyvin
vaikeana tai jopa mahdottomana monissa tutkimusympäristöissä
(Matsumoto 2010: 142). On erittäin haastavaa kerätä niin täydellinen
aineisto, että informantit voitaisiin oikeasti pisteyttää tietyn
mallin mukaan. Tällöin koko aineiston keruun lähtökohdaksi pitäisi
ehkä ottaa itse verkostojen analyysi, mikä on siten ongelmallista,
että haastatteluihin tarvitaan joka tapauksessa muutakin
vertailukelpoista sisältöä. Aloin tästä lähtökohdasta pohtia, kuinka
verkostoanalyysi olisi sovellettavissa karjalaisiin ja komilaisiin
yhteisöihin. Informanttien toisiinsa kytkeminen tuntui kuitenkin
lähtökohtaisesti erittäin tärkeältä ja käyttökelpoiselta tiedolta.

Nyt käyttämäni kielelliset verkostot ovat käytännössä laajennettuja
sukupuita, jotka osoittavat ja ajoittavat eri henkilöiden välillä
kuvattua kielenkäyttöä. Vastaavaa perheen sisällä tapahtunutta
muutosta on kuvannut aiemmin Riho Grünthal tarkastellessaan
kielenvaihtoa vepsäläisen informantin kohdalla (Grüthal 2009:
284). Oma mallini on saanut vaikutteita häneltä, mutta tulee hyvin
lähelle erityisesti nahuatlia ja saamelaiskieliä tutkineen Vendula
Hingarován kehittämää tapaa osoittaa sukupuiden avulla kielenvaihdon
etenemistä (Hingarová 2003: 120–125). Olen omaksunut hänen mallistaan
muun muassa yleiset käyttämäni konventiot, vaikka yksityiskohdissaan
tapamme havainnollistaa sukupuita eroavatkin jonkin verran. Hieman
vastaavaa mallia on hyödyntänyt myös Vantaan suomenkielistymistä
tutkinut Marika Tandefelt kartoittaessaan neljän eri sukupolven
kielitaitoa (Tandefelt 1994: 260).

Uskon, että Karjalassa ja Komissa olisi mahdollista kerätä erittäin
korkeat kriteerit täyttävää aineistoa, mutta se vaatisi
lähtökohtaisesti enemmän aikaa. Muutamassa viikossa on mahdotonta
saada sirpaleista otosta laajempaa aineistoa. Väitän silti, että
tällainenkin aineisto on käyttökelpoisempaa kuin sellainen, josta
kaikki tieto keskinäisistä suhteista puuttuu. Käsittelenkin tämän
takia aineistoa verkostojen kautta, mutta pidättäydyn hyödyntämättä
minkäänlaista matemaattista mallia. Myös Anneli Sarhimaa on aiemmin
epäillyt tällaisen informantteja tietyn mallin mukaan pisteyttävän
lähestymistavan toimivuutta ja kehottanut etsimään vaihtoehtoisia
malleja (Sarhimaa 2009: 176–179). Tämä ratkaisu tietysti
kyseenalaistaa termin sosiaalinen verkosto käyttökelpoisuuden oman
tutkimukseni kohdalla. Termi kuten kielellinen verkosto tai
puheverkosto voisi olla neutraalimpi. Käytännössä termiä sosiaalinen
verkosto käytetään hyvin erilaisista tutkimuksista, joten käytän sitä
itsekin. Hingarován mallin mukaisesti haluan tarkastella verkoston
kautta myös sellaisia henkilöitä, joita en ole vielä haastatellut,
sillä tarkoituksena on soveltaa verkostoanalyysia informanttien
sukupuiden, keskinäisten suhteiden ja kielenvaihdon erilaisten
etenemisskenaarioiden mallintamiseen. Väitän, että näinkin on
mahdollista tuoda esiin kielenvaihdon yksityiskohtia, jotka eivät
muunlaisella visualisoinnilla tule näkyviin. En käsittele voiko
sosiaalisten verkostojen rakenteella selittää kielenvaihtoa, vaan
pystyykö niillä mallintamaan ja kuvaamaan sitä. Pikemminkin kyseessä
on havainnollistamiskeino ja esitystapa, jolla pystyn asettamaan
yksittäisten informanttien kerronnan ja kuvauksen sellaiseen
kontekstiin, jota ei syntyisi ilman sosiaalisten suhteiden
tarkastelua. Samalla tämä on alku laajemmalle mallille verkostojen
analyysista, jota tulen kehittämään tulevina vuosina aineistojen
karttuessa.

Olen käyttänyt sukupuiden verkostoissa samoja värejä kuin
domeenianalyysissa. Olen merkinnyt eri henkilöiden käyttämän kielen
värillisellä nuolella, lukuun ottamatta puolisoita. Heidät on merkitty
paksulla horisontaalisella viivalla. Aineistossa ei ollut yhtään
tapausta, jossa aviopuolisot olisivat puhuneet toisilleen eri kieliä,
joten tässä ei tarvinnut ilmaista suhteen vuorovaikutteisuutta. Osa
venäjänkielisistä aviopuolisoista on oppinut ymmärtämään
kielenvaihdossa väistyvää kieltä, mutta tämä ei liity heidän rooliinsa
kielen käyttäjänä vaan kuulijana. Tarkastelen, tuleeko tällainen rooli
esiin verkostoissa. Analyysini kannalta tärkeät informantit on
numeroitu viittaamisen helpottamiseksi. Henkilön kohdalla oleva tyhjä
keskus tarkoittaa, että hän ei asu tässä nyt tutkitussa yhteisössä.

Domeenianalyysin ja verkostojen analyysin taustaksi käsittelen
kielenvaihdon etenemistä Tuuksessa ja Koigortissa erilaisten
tilastoitavien muuttujien avulla. Tällaisia ovat informanttien ikä,
sukupuoli, kotipaikka sekä raportoitu puolison ja lasten
kielitaito. Tällaisen informaation kerääminen kuuluu
sosiolingvististen haastattelujen perussisältöön, vaikka
haasteellisista työolosuhteista johtuen aina ei tarkkoja tietoja ole
saatu. Esimerkiksi henkilötietoja hyvin tarkasti kartottaneista
haastatteluista on voinut jäädä puuttumaan vapaampaa keskustelua ja
pidempää kerrontaa, aivan jo ajan puolesta syntyneiden rajoitusten
takia. Vapaammin edenneissä haastatteluissa puolestaan voi olla
toisenlaisia aukkoja tietyissä yksityiskohdissa. Ei ole yllättävää,
että esimerkiksi kielenoppimista ja domeenien kielenkäyttöä
käsittelevissä taulukoissa on keskenään erilainen määrä
informantteja. Mielestäni on täysin luonnollista, että
kenttätyöhaastatteluina kerätystä aineistosta puuttuu osia, eikä tätä
ole syytä peitellä tai kaunistella liikaa. Täydellistä aineistoa ei
varmasti ole kenenkään käytössä. Toisaalta on täysin mahdollista
esittää taulukossa, mikä osa aineistosta on kattavammin ja mikä
puutteellisemmin kerätty. Tämä vain korjaa osaltaan tutkijan positiota
suhteessa aineistoon ja selkeyttää lukijan mahdollisuuksia arvioida
tutkimuksen väitteitä. Tuuksen aineistoa oli mahdollista täydentää
kesällä 2013, minkä johdosta se on huomattavasti Koigortin dataa
täydellisempää.
