# Yhteenveto

## Johtopäätökset

Tutkimuksen keskeisenä tuloksena on, että Koigortissa komin kieli on
ainakin sporadisesti välittynyt lapsille meidän päiviimme
asti. Tuuksessa kielenvaihdon prosessi vaikuttaa laajemmalta ja
kokonaisemmalta – nuoria aktiivipuhujia ei vaikuta
olevan. Tutkimukseen ei kuitenkin kuulunut minkäänlaista arviota
kielitaidosta, johtuen aiemmin esittelemästä tähän tematiikkaan
liittyvästä problematiikasta. Käytännössä kielenvaihtoa olisikin ehkä
tarkasteltava muuttuneen kielenkäytön sijasta muuttuneina diskursseina
ja käsityksistä kielitaidosta. Tästä on vihjeitä työssäni, mutta
minulla ei ole ollut mahdollisuutta perehtyä aiheeseen
syvällisemmin. Käytännössä kielen välittyminen lapsille ei ole vielä
lakannut Tuuksessakaan, muutos on pikemminkin tapahtunut olosuhteissa,
joissa aktiivisia kielenkäyttäjiä voi kasvaa.

Aloitin analyysini tarkastelemalla kielenoppimisen domeeneja. Tämän
perusteella 1920- ja 1930-luvuilla syntyneet ovat oppineet melko
myöhään, moni vasta armeijassa tai sodan jälkeen. Venäjän
oppimisdomeeni on kuitenkin muuttunut siten, että Tuuksessa on alettu
oppia venäjää ennen kouluikää 50-luvulla. Tämä sopii ajallisesti
yhteen kylään muuttaneiden muunkielisten antaman kuvauksen
kanssa. Käytännössä karjala on kuitenkin kestänyt kauan kotikielenä,
mutta perhekohtaisesti venäjästä on alkanut tulla toinen kotikieli
1960- ja 1970-luvuilla. Tässä on kuitenkin vaihtelua, sillä
informanttien joukossa on myös 1970-luvulla syntyneitä, jotka ovat
oppineet venäjää vasta päiväkodissa. Muutosta koulussa käytetyssä
kielessä voi verrata poliittisiin muutoksiin, joissa koulukieli
vaihdettiin tietoisesti venäjäksi. On kuitenkin selvää, ettei tämä
välittömästi johtanut kielen käytön lopettamiseen tässä ympäristössä.
Erityisesti Tuuksen aineiston perusteella lapset ovat käyttäneet
karjalaa keskenään koulussa vielä 1970-luvulla. Koigortin aineistosta
tätä muutosta ei oikein voi ajoittaa, mutta erityisesti vanhimpien
sukupolvien venäjänoppiminen kouluympäristössä ei näytä välttämättä
johtaneen venäläistymiseen. Aineisto sinällään viittaisi venäjän
olleen selvemmin koulussa opittu kieli näiden vanhempien komilaisten
informanttien keskuudessa. Tämä ehkä heijastelee Komin poliittisesti
selkeämpää asemaa Neuvostoliiton alkuaikoina, mutta ei vielä kerro
vallinneista koulukäytänteistä. Tätä voi verrata Bernard Spolskyn
tutkimukseen navajon kielenvaihdosta, jonka perusteella
sisäoppilaitokset eivät vuosikymmenienkään aikana johtaneet
varsinaiseen englanninkielistymiseen, sillä niiden rahoitus ja
opetuskäytännöt olivat niin heikkoja (Spolsky 2002:
143). Mahdollisesti Komissa tähän kytkeytyvät kaoottiset sota-ajat,
eikä valtavien työläis- ja vankimassojenkaan siirtäminen alueelle ole
välttämättä ollut täysin onnistuneesti koordinoitu projekti. Myös
Komissa näyttää siltä, että viimeistään 1980-luvulla venäjä on
muuttunut myös kotona opituksi kieleksi. Tämä olisi kuitenkin
yleisesti ottaen joitain vuosikymmeniä myöhemmin kuin
Tuuksessa. Tuuksssa kaikkein nuorimpien informanttien kohdalla näkyy,
että karjalan oppiminen on alkanut yhdistyä myös domeeniin koulu, mikä
tarkoittanee tässä tapauksessa karjalan roolin heikkenemistä kotona ja
koulun jäämistä ainoaksi domeeniksi, jossa kieli on opetuksen kautta
läsnä.

Muualta Tuukseen ja Koigortiin muuttaneita informantteja on
aineistossa paljon. Heidän erillinen tarkastelunsa antoi viitteitä
siitä, että heidän kansallisuuttaan tai kielitaitoaan tärkeämpi
muuttuja olisi aika, jolloin kylään on muutettu. Myöhemmin kielellisiä
verkostoja tarkastellessani pystyin havainnollistamaan, että
1900-luvun alkupuolella sekä Tuukseen että Koigortiin muuttaneet ovat
usein omaksuneet karjalan tai komin käyttökielekseen. Tuuksessa
tällainen assimiloituminen on lakannut 50-luvulla, tämän vuosikymmenen
näyttäessä hyvin keskeiseltä koko yhteisön venäjän taidon
kehittymiselle. Kuitenkin sekä Tuukseen että Koigortiin 1950-luvulla
muuttaneet lapset ovat oppineet paikallista kieltä, vaikka aikuisiällä
kokevatkin venäjän vähintään yhtä vahvaksi kielekseen kuin karjalan
tai komin. Sama on luonteenomaista myös 1950- ja 1960-luvun vaihteessa
syntyneen venäläisen informantin lapsille.

Kyliin muuttaneet muut itämerensuomalaiset ovat pääasiassa
venäläistyneet kieleltään, ainoan poikkeuksen muodostuessa
yksittäisistä lyydiläisistä. Inkerinsuomalaiset tai vepsäläiset eivät
näin ollen näytä eroavan samoilla vuosikymmenillä kylään muuttaneista
valkovenäläisistä tai venäläisistä, sillä kaikki nämä ryhmät kuvaavat
ymmärtävänsä karjalaa, vaikkeivät ole koskaan puhuneet
sitä. Äidinkieleltään muut kuin karjalaiset tai venäläiset osasivat
vielä äidinkieliään, mutta kuvasivat niiden käyttömahdollisuuksia
hyvin rajallisiksi. Jostain syystä näille ihmisille ei ole tullut
yhteisössä roolia karjalan käyttäjänä, mutta heidän passiivinen
kielitaitonsa paljastaa heidän kuulleen kieltä riittävästi tällaisen
taidon kehittymiseksi.

Domeenin perhe tarkastelu osoitti, että Tuuksessa jo 30-luvulla
syntyneet ovat puhuneet omien lastensa kanssa usein venäjää. Heidän
lapsensa edustavat jo sukupolvea, joka on puhunut puolisoidensa kanssa
venäjää. Tämä yleistyy melko jyrkästi 40-luvun lopulla syntyneiden
keskuudessa. Koigortissa näkyy vastaava muutos kielenkäytössä puolison
kanssa, mutta se on sporadisempaa, perhekohtaisempaa. Perheen
sisäisestä kielenkäytöstä näkee sen, ettei Tuuksessa ole nähtävissä
sukupolvea, joka olisi puhunut omien lastenlastensa kanssa vain
karjalaa. Komissa tämä on tapauskohtaista. Ajoittain kieli on säilynyt
esimerkiksi 40-luvulla syntyneiden lapsenlapsenlapsille. Molempien
kylien aineistossa on melko yleistä, että eri osa lapsista osaa
karjalaa tai komia ja osa ei. Nykyaikaa kohti tullessa tämä ilmiö
näyttää siirtyvän informanttien lapsenlapsista omiin lapsiin,
heijastellen tässä mielessä ajallista muutosta.

Pyrin kuvaamaan kielellisillä verkostoilla tämän muutoksen
yksityiskohtia. Sekä Karjalassa että Komissa on toistunut malli, jossa
iäkkäimmän karjalaa tai komia aktiivisesti käyttäneen sukupolven
kuolema on katkaissut kielen siirtymisen lapsille. Huomauttaisin, että
kieli vaikuttaa siirtyneen tähän pisteeseen asti jossain määrin. Tämän
väestönosan yhä ollessa elossa, ovat siis myös läsnä jonkinlaiset
mahdollisuudet kielen transmission onnistumiselle. Silti kielenvaihto
voi olla laajassakin perheessä erittäin nopea ja totaalinen, kuten
ensimmäiset Tuuksesta ja Koigortista tarkastelemani sukupuut
havainnollistivat. Yleinen malli on, että vanhimmat lapset osaavat
karjalaa tai komia. Nancy Dorian puolestaan havaitsi tutkiessaan
domeenia perhe skottigaelin puhujien parissa, että nimenomaan
monilapsisten perheiden nuorimmat lapset eivät osanneet gaelia
kunnolla. Dorian kuvaakin heitä termillä semi-speaker (Dorian 1981:
107). Nyt esittelemissäni tapauksissa vanhimmatlapset oppivat jossain
määrin komia tai karjalaa, mutta heistä ei tullut välttämättä
aktiivipuhujia, nuorempien osatessa tai käyttäessä kieltä tätäkin
vähemmän. Ei ole selvää, liittyykö tällainen variaatio kielenvaihdon
vaiheeseen, vai ovatko mallit erilaisia eri yhteisöissä.

Molemmissa yhteisöissä domeenin koti kuvattiin venäläistyneen
informanttien elämän aikana. Käytännössä tämä on tarkoittanut
Tuuksessa domeenin voimakasta venäläistymistä, siinä missä Koigortissa
domeenia kuvataan nykyään pääosin kominkieliseksi tai
kaksikieliseksi. Tuuksen aineistossa kodin kaksikielisyys näyttää
edeltäneen sen venäläistymistä, mutta toisaalta Tuuksen kaksikielisyys
vaikuttaa aineistoni perusteella huomattavasti vähemmän vakaalta kuin
Koigortissa.

Domeeneista kaikkein vähiten ajallista muutosta kokenut muodostuu
naapureista. Koigortin aineisto on niin yksipuolinen, että se jopa
tuntuu aineistonkeruun virheeltä. Mieleen nousee, olenko esittänyt
kysymyksen jotenkin vaikeasti käsitettävällä tavalla Komissa?
Käytännössä tämä domeeni näyttää kuitenkin niin vakaalta myös
Tuuksessa, ettei tämä nähdäkseni ole ainoastaan ongelma aineistossa
itsessään. Tuuksessa näkyy tendenssi, että nuoret käyttävät vähemmän
karjalaa naapureiden kanssa kuin iäkkäämmät informantit. Kylien
välillä on ero siinä, kuinka Tuuksessa koti on vähemmän karjalainen
domeeni kuin naapurit, siinä missä Koigortin tilanne on
päinvastainen. Koigortissa vielä domeeni kylä nähdään tästä astetta
venäläisempänä. Molemmissa yhteisöissä kielivalintaa näissä
ympäristöissä vaikuttaa leimaavan tuttuus. Karjalaa tai komia
käytetään heidän kanssaan, jotka ovat aina puhuneet tätä kieltä. Nämä
tutut henkilöt kuitenkin levittäytyvät tällaisissa kyläyhteisöissä
huomattavasti kauemmas kuin perheenjäsenten tai lähinaapureiden
pariin. Toinen komista esittelemäni verkosto kuvasi juuri tapausta,
jossa komia on opittu perheen ulkopuolella kahdessa sukupolvessa. Tämä
kertoo jotain olennaista domeenien koti ja naapurusto tai kylä
suhteista. Tietyssä mielessä voi olla tärkeämpää, että naapurusto ja
kylä ovat tietynkielisiä kuin että koti olisi. Luonnollisesti
vaikuttaa olennaiselta myös keitä nämä naapurit ovat. Jos naapuruston
karjalaisuus tai komilaisuus selittyy sen iäkkäillä asukkailla, ei
tämä vielä kerro paljoakaan nuorten asukkaiden keskinäisistä
verkostoista.

Tämä tuttuus näkyy myös domeenia kauppa tarkasteltaessa. Toisaalta
siten, että kaupan työntekijöiden ajatellaan vaihtuvan nykyään
useammin kuin ennen. Vedotaan siihen, ettei heidän kielitaitoaan voi
tietää. Toisaalta Tuuksessa tiedetään, että vanhimmat ikäluokat
käyttävät karjalaa kaupassa, ja erityisesti Tuuksessa yleisin
kielivalinta kaikissa ikäluokissa kohdistuu molempiin
kieliin. Tietyssä mielessä tämä voisi viitata Koigortin vakaampaan
kaksikielisyyteen. Varsinaisesti nyt ei ole keinoja arvioida
tätä. Tuuksessa tuli esiin, että nuorien asiakkaiden kanssa käytetään
venäjää ja iäkkäiden kanssa karjalaa. Näin kuvasi nuorten
perspektiivistä noin 40-vuotias karjalaa puhuva nainen. Vanhempien
ikäryhmien kohdalla tässäkin näkyy sporadisuutta.

Domeenissa työ ammattia tärkeämmältä vaikutti informanttien ikä. Tästä
kuitenkin erottuu tendenssi, että lääkärit, opettajat ja johtajat
käyttävät yhtenäisemmin venäjää kuin muut ammattiryhmät. Tämä on
mielenkiintoinen tulos, ja sinällään suhtautuu domeeneihin lääkäri ja
koulu. Domeenin koulu osalta on selvää, että Karjalassa 50-luvulla
tullut kielto käyttää karjalaa on aiheuttanut hyvin dramaattisia
muutoksia. Tässä on kuitenkin havaittavissa selvää viivettä. Vielä
1960-luvulla syntyneet saattavat kuvata naureskellen, että toki
poikien kanssa puhuttiin karjalaa, vaikka kiellettiin. Toisaalta osa
tätä vanhemmista informanteista syyttää juuri tätä kieltoa kielen
käytön vähentymisestä ja perustelee venäjänkäyttöään
sillä. Haastattelin myös 1970-luvulla koulua käynyttä informanttia,
joka kuvaili tällaisten kieltojen loppuneen ennen hänen menoaan
kouluun. He käyttivät keskenään muiden lasten kanssa. Osoitin
myöhemmin sosiaalisia verkostoja tarkastellessani, että osa juuri
näistä verkostoista on säilynyt tähän päivään asti. Lasten varhain
kehittynyt venäjäntaito näyttää kuitenkin yleiseltä näihin aikoihin
tultaessa, ja 1980-luvulla koulua käynyt karjalaa osannut nainen
kertoi olleensa ikäryhmänsä ainoa karjalaa osannut. Vielä nykyäänkin
yksittäisiin nuoriin yhdistetään heidän karjalan osaamisensa, mutta
käytännössä he eivät vaikuta karjalan aktiivikäyttäjiltä. Koigortissa
puolestaan ei ole varsinaisesti läsnä kieltoa käyttää
komia. Koulukieli on vaihtunut, mutta tähän liittynyt diskurssi on
erilainen. Tietyt nuoret osaavat kieltä hyvin ja käyttävät sitä
aktiivisesti.

Mitä tämä tarkoittaa tasavaltojen kontekstissa? Tarkasteltu Tuuksen
kylä sijaitsee kaikkein karjalaisimmalla alueella tasavallassa, mutta
tästä huolimatta tilastollisesti venäläisemmällä Koigortin alueella
kieli on säilynyt paremmin. Aiemman tutkimuksen perusteella ei näytä
todennäköiseltä, että karjalan kieli olisi välittynyt olennaisesti
enemmän lapsille muissakaan suurissa aiemmin karjalankielisissä
yhteisöissä. Komissa on kuitenkin viitteitä siitä, että Grivan
kaltaisia kieltä vahvasti säilyttäneitä kyliä olisi vielä eri puolilla
tasavaltaa, ja Koigortin kaltaisia sinällään venäläistyneitä rajonin
keskuksia on varmasti. Tutkimukseni perusteella ei ole ollenkaan
selvää, että keskuskylät olisivat niin venäläistyneitä kuin usein
tunnutaan ajattelevan. Toisaalta Komissa on runsaasti täysin
venäläistyneitä kyliä, eikä kielen elinvoimaisuutta voi päätellä
minkään ulkoisten mittareiden avulla. Osa venäläistyneistä kylistä on
rakennettu asumattomille paikoille metsätyökeskuksiksi, mutta
ajoittain väestöä on keskitetty myös vanhoihin komilaisiin
kyliin. Komilaisten osallistuminen metsätyökeskusten töihin on
nopeuttanut kielenvaihtoa, mutta paikallisyhteisöt ovat ainakin vielä
1950-luvulla automaattisesti toimineet tätä vastaan, siten että
venäläistyneet lapset ovat oppineet komia omalta ikäryhmältään.

Verrattaessa muualla maailmassa tehtyihin tutkimuksiin muistuttaa
kielenvaihdon eteneminen domeeneittain erityisesti Susan Galin
kuvausta Itävallan unkarilaisista, joiden kielenvaihdon etenemistä hän
tarkasteli yksittäisten henkilöiden tasolla (Gal 1979). Galin
tutkimuksen perusteella saksan kieli yhdistettiin moderniuteen ja
unkari erityisesti maatalouteen. Britannian kiinalaisväestöä tutkineen
Li Wein mukaan henkilön kiinalaisuus oli ratkaiseva piirre valittaessa
tämän kanssa käytettyä kieltä (Li Wei 1994). Oman aineistoni
perusteella venäläisyys on Tuuksessa ja Koigortissa kielivalinnalle
keskeinen muuttuja. Venäläisyys ja venäjänkielisyys kuitenkin
indeksoituu erityisesti nuoriin, mikä näyttää monissa tilanteissa
olevan ristiriidassa nuorten oikean kielitaidon kanssa.

Kielellisten verkostojen kannalta olennaisesti kielen käyttöön
vaikuttavilta näyttävät isovanhempien läsnäolo samassa kodissa sekä
oman ikäryhmän lasten ja nuorten käyttämä kieli. Aineistossa on
lukuisia esimerkkejä kielitaidon kehittymisestä kaksikielisempään
suuntaan isovanhempien asuessa lasten kanssa samassa
taloudessa. Tällaiset tilanteet ovat käytännössä nykyäänkin jatkuvia.

## Jatkotutkimuksessa huomioitavaa

Jatkotutkimusta tehdessä voisi ottaa paremmin huomioon sen, että
kielen välittyminen lapsille näyttää jatkuvan jossain muodossaan
siihen asti, kunnes väistyvää kieltä aktiivisesti käyttävä sukupolvi
kuolee. Tämä ei tapahdu yhtäkkiä, minkä lisäksi yksittäisten
henkilöiden rooli voi olla erittäin suuri. Esittelin tällaisia
tilanteita potentiaalisia kielen transmissioita käsittelevissä
verkostoissa. Näissä näkyy esimerkiksi Mark Sicolin mainitsema
epäselvä toimijuus. Pienen kieltä vielä osaamattoman lapsen ympärillä
on ihmisiä, jotka voivat kielen välittymisen tärkeäksi, ja Tuuksen
esimerkin kohdalla perheen äiti otti roolia tämän varmistamisessa
puhumalla lapselle karjalaa. Huomaamme kuitenkin suuria ristiriitoja
eri henkilöiden asenteissa, oletuksissa ja näihin perustuvassa
toimijuudessa. Esimerkiksi esimerkin Karjala II isoäiti voisi hyvin
toimia karjalan siirtäjänä, mutta pääosin ideologisista syistä ei ota
tätä roolia. Kielenvaihtoa voi tarkastella tämänkin aineiston pohjalta
lähes sadan vuoden ajalta, eikä näinkään pitkässä otoksessa
varsinaisesti näy kielenvaihdon alku- eikä loppupäätä. Vaikka lapset
vaikuttaisivat venäjänkielisiltä, monet karjalan tai komin oppimisen
edellytykset ovat yhä olemassa ja nähtävästi nytkin kasvava nuorin
sukupolvi saattaa oppia kieltä passiivisesti hyvin paljon. Tulisikin
kiinnittää huomiota juuri mahdollisuuksiin aktivoida tätä passiivista
kielitaitoa, ja huomata, että sen kehittymisen ehdot jatkuvat hyvin
kauan aikaa kielenvaihdon jo alettua. On myös huomattava
paikallisyhteisöjen muuttuneen hyvin kokonaisvaltaisesti tutkittuna
aikana. Uusia asukkaita on muuttanut ja moni muuttanut
pois. Ehdottaisin varovaisesti, että kielenvaihdon tärkein
tapahtumapaikka on epäilemättä siirtynyt pois kylistä kaupunkeihin, ja
näiden verkostojen tarkastelun pitäisi olla jatkotutkimuksen keskeisiä
tavoitteita.

Lupasin sivulla 30 ottaa kantaa siihen, kuinka hyödyllistä on kerätä
samanaikaisesti kielisosiologista aineistoa ja yhteisön perinteistä
muistitietoa. Tämän ohella on usein kerätty myös paikannimiä. Olen
sitä mieltä tutkimuksen nykyisessä vaiheessa, että oikeissa
mittasuhteissa nämä lähestymistavat tukevat toisiaan. Pelkkä
kielisosiologinen aineisto yksinään ei riitä, jos ympäröivän
kyläyhteisön historiallisesta kontekstista ei ole mitään tietoa. Silti
pelkkään vapaampaan narratiiviin perustuvaan aineistoon voi olla
todella vaikea soveltaa tarkempia tutkimuskysymyksiä, sillä
aineistosta ei voi edes tutkimuksen aluksi poimia tiettyjä
säännöllisesti toistuvia teemoja tai vastauksia. Erilaisten
keräysmetodien yhtaikainen käyttö on kuitenkin siten perusteltua, että
informantit eroavat toisistaan niin paljon. Tutkijoita on niin vähän,
että tietyssä mielessä on jokaisen velvollisuus kerätä aineistoa oman
kapean erityisalansa ulkopuolelta. Muut voivat kuitenkin hyödyntää
aineiston nyt käyttämättä jääneitä osia myöhemmin. Liitteinä 1 ja 2
olevat kaavakkeet osoittavat tutkimuksen aikana kerätyn tietoa hyvin
erilaisista aiheista. Selvästi tulevaisuudessa on tehtävä tarkempaa
rajausta, mikä toisaalta on hyvin vaikea päätös tällaisia huonommin
tutkittuja yhteisöjä käsiteltäessä.

Domeenianalyysia täytyy mielestäni kehittää yhdistämällä sitä
laajempaan etnografiseen tutkimukseen. Lähtökohdaksi on otettava
paikallisyhteisöjen elämäntapa ja tässä läsnä olevat kielenkäytön
ympäristöt. Perheen sisällä olevia rooleja voisi täydentää nuoremmilla
ja vanhemmilla sisaruksilla erikseen. Olen ajoittain muissa
yhteyksissä kartoittanut kielenvaihtoa serkkujen ja sisarusten lasten
keskuudessa, mikä usein näyttää antavan selvän kuvan kielenvaihdon
laajuudesta. Kielellisten verkostojen analyysin kannalta olisi tärkeä
saada enemmän tietoa nyt sporadisesti havaituista lateraalisista
verkostoista. Kielenvaihdon tutkimuksessa usein korostetun ydinperheen
rinnalle on nostettava omanikäisten vertaisryhmien
rooli. Synkronisesti voitaisiin tarkastella nuorten ja lasten
muodostamia toimintayhteisöjä. Tämä olisi erittäin hyvä tutkimustapa
yhteisöissä, joissa paikallinen kieli on hyvin elävä. Kielelliset
antropologit (linguistic anthropology) ja kielellisen sosialisaation
(language socialization) tutkijat ovat jo osoittaneet niiden tapojen
tärkeyden, joilla aikuiset ja erityisesti kasvattajat puhuvat
lapsille. Tällaisista käytännöistä suomalais-ugrilaisissa yhteisöissä
ei ole mitään tietoa. Tutkimuskenttä on täysin auki ja mahdollisuudet
erittäin hyvät.

## Loppusanat

Käsittelen vielä tutkimukseni lopuksi kenttätöiden aikana kerättyä
sporadisempaa etnografista aineistoa. Yksittäiset tiedonannot
kuitenkin osoittavat nyt käytettyjen mallien rajallisuuden, mitä on
mielestäni pakko korostaa. Työskennellessämme Tuuksessa kesällä 2013
olimme majoittuneita joidenkin kilometrien päähän varsinaisesti
työseudustamme. Vietimme iltaisin hyvin paljon aikaa odottaen
tilaamiemme taksien saapumista. Varsinaiset työt oli jo saatu
päätökseen ja alkoi olla turhan myöhäistä etsiä uusia
informantteja. Paikalliset lapset ajelivat poikkeuksetta
polkupyörillään meidän lähellämme. Keskustelimme heidän kanssaan
pääasiassa venäjäksi, mutta tietysti olimme kiinnostuneita tietämään,
kuinka paljon he osaisivat karjalaa. Kerroimme olevamme Suomesta ja
tutkivamme karjalan kieltä ja kulttuuria. Suorat kysymykset eivät
tuottaneet juurikaan vastauksia, lähinnä naurua ja juoksua luotamme
pois. Pojat käyttivät keskenään pelkkää venäjää. He suhtautuivat
läsnäoloomme ystävällisesti, kuten muutkin kyläläiset poikkeuksetta
tekivät.

Tilanne kuitenkin muuttui iltojen kuluessa ja epämuodollisen
vuorovaikutuksen muuttuessa säännöllisemmäksi. Haastattelumaisten
kysymysten sijasta aloin osoittaa enemmän mielenkiintoa heidän
polkupyöriään ja lomaharrastuksiaan kohtaan. Lapset olivat
kiinnostuneita meistä, ja osa heistä alkoi reagoida suomenkieliseen
keskusteluumme tuntemillaan suomenkielisillä fraaseilla. Tämä oli
siten odotettavaa, että tiesimme monien lasten opiskelevan suomea
koulussa. Aloin osoittaa omia puheenvuorojani lapsille karjalaksi
milloin vain mahdollista. Yllätyksekseni eräs heistä vastasi lukuisia
kertoja normaalilla ja spontaanilla karjalalla. Esimerkiksi
ihmetellessäni onko ohi ajava auto mahdollisesti meidän taksimme,
vastasi noin 12-vuotias poika, että Saša ajelou. Valitettavasti en
pystynyt nauhoittamaan näitä vuorovaikutustilanteita, mutta nähdäkseni
lapsen tuottama karjala oli morfologisesti täysin adekvaattia
paikallista livviä. Luonnollisesti kyseessä on vain oma vaikutelmani,
mutta ainakaan näiden lyhyiden kohtaamisten aikana en havainnut
kielessä mitään kummallista.

Tätä tietoa on syytä verrata esittelemiini domeenien- ja sosiaalisten
verkostojen analyyseihin. Erityisesti Tuuksen aineistonperusteella
nuorimmat sukupolvet ovat hyvin voimakkaasti venäläistyneet. On
kuitenkin kysyttävä, missä määrin tämä on aineiston keruutavasta ja
yhteisössä vallitsevista diskursseista vääristynyt kuva. Näidenkään
lasten karjalantaito ei tule esiin missään analyysin osassa, eivätkä
he ilmeisesti käytä karjalaa missään domeeneissa tai sosiaalisissa
verkostoissa. Mieleeni palaa Annette Schmidtin kuvaus kenttätöistään
dyirbalin puhujien parissa, jolloin häneltä kesti kahdesta kolmeen
kuukautta saada itsensä ikäisiä nuoria käyttämään dyirbalia hänen
kanssaan (Schmidt 1985: 7). Onko vaarana, että lyhyillä
kenttätyöjaksoilla kerätty aineisto johdattelee vääriin
johtopäätöksiin? Pidän tätä hyvin todennäköisenä. Toisaalta Tuuksen ja
Koigortin aineistojen vertailu kertoo toistettujen kenttätyöjaksojen
hyvistä mahdollisuuksista: Tuuksen aineisto on ehdottomasti parantunut
kahden kenttätyöjakson myötä. Aineiston analysoimisen hitaudesta
johtuen säännöllisesti toistetut kenttätyöjaksot, joiden välisillä
tauoilla edellisen matkan aineisto on kattavasti purettu ja
analysoitu, voi olla paras tiettyihin yhteisöihin sovellettava
tutkimustapa. Yksittäiset hyvin pitkät kenttätyöjaksot eivät sinällään
ratkaise kaikkea, sillä aineiston analyysin kannalta voi olla parasta
työskennellä muualla kuin kenttätyöolosuhteissa. Jo muutamina
viikkoina kerätyn aineiston analyysiin menee kuukausia, joten ei ole
yksiselitteisesti perusteltua, että aineistoa kerättäisiin aina hyvin
pitkissä jaksoissa.

Aineiston huolellista analysointia korostaa sekin, että uuden
tutkimuksen vieressä on usein hyllymetreittäin vanhaa
aineistoa. Suomalais-ugrilaiset kielet eivät ole kuvaamattomia
kieliä. Erityisesti Karjalasta näyttää olevan tuhansia tunteja
nauhoituksia (Kotimaisten kielten tutkimuskeskusken arkisto,
Juminkeko-säätiön arkisto jne.). Varsinaisia vanhoja kielisosiologisia
tutkimuksia ei ole, mutta vanhoja aineistoja olisi silti syytä käyttää
enemmän hyödyksi. Esimerkiksi variaationtutkimukselle olisi loistavia
mahdollisuuksia etsimällä eri vuosikymmenillä haastateltujen
informanttien sukulaisia ja tuttavia. Usein puutteellista metadataa
voisi periaatteessa täydentää vanhojen kielimestarien vielä ollessa
joko elossa tai elävinä heidät tunteneiden muistoissa. Oma kokemukseni
Komista osoittaa, että aineiston vanhetessa alkavat ihmisetkin
unohtua, eikä jossain vaiheessa ole enää mahdollista yhdistää
esimerkiksi vuosisadan alkupuolella haastateltuja informantteja
nykyään näissä yhteisöissä eläviin ihmisiin. Tilaisuuteen on
tartuttava pian.
